package com.elminster.jcp.compile.control;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.context.CompileContext.LoopLabels;
import com.elminster.jcp.compile.exception.CompileException;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for break statements inside loops.
 *
 * <p>Generates an unconditional jump to the end label of the innermost loop.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: break;
 * GOTO endLabel       // jump to loop's end label
 * }</pre>
 *
 * <h4>Example in Context:</h4>
 * <pre>{@code
 * // while (true) { if (x > 10) break; x++; }
 *
 * startLabel:
 * ICONST_1                     // push true
 * IFEQ endLabel                // (never taken)
 * ILOAD x                      // check x > 10
 * BIPUSH 10
 * IF_ICMPGT breakTarget
 * ICONST_0
 * GOTO skipBreak
 * breakTarget:
 * ICONST_1
 * skipBreak:
 * IFEQ skipBreakBody
 * GOTO endLabel                // <- break statement
 * skipBreakBody:
 * IINC x, 1                    // x++
 * GOTO startLabel
 * endLabel:                    // <- break jumps here
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>No stack change (unconditional jump)</li>
 * </ul>
 *
 * @throws CompileException if break is used outside a loop
 * @see com.elminster.jcp.eval.control.BreakEvaluator
 */
public class BreakCompiler extends ControlCompiler {

    public BreakCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        LoopLabels loop = ctx.currentLoop();
        if (loop == null) {
            throw new CompileException("break statement outside of loop", getSourceLocation());
        }

        // Jump to the end of the loop
        mv.visitJumpInsn(Opcodes.GOTO, loop.getEndLabel());
    }

}
