package com.elminster.jcp.compile.control;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import com.elminster.jcp.compile.context.CompileContext.LoopLabels;
import com.elminster.jcp.compile.exception.CompileException;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for continue statements inside loops.
 *
 * <p>Generates an unconditional jump to the start label of the innermost loop,
 * skipping the rest of the loop body and restarting from the condition check.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: continue;
 * GOTO startLabel     // jump to loop's start label
 * }</pre>
 *
 * <h4>Example in Context:</h4>
 * <pre>{@code
 * // while (x < 10) { if (x == 5) continue; print(x); x++; }
 *
 * startLabel:                  // <- continue jumps here
 * ILOAD x                      // check x < 10
 * BIPUSH 10
 * IF_ICMPLT condTrue
 * ICONST_0
 * GOTO condEnd
 * condTrue:
 * ICONST_1
 * condEnd:
 * IFEQ endLabel
 * ILOAD x                      // check x == 5
 * ICONST_5
 * IF_ICMPEQ eqTrue
 * ICONST_0
 * GOTO eqEnd
 * eqTrue:
 * ICONST_1
 * eqEnd:
 * IFEQ skipContinue
 * GOTO startLabel              // <- continue statement
 * skipContinue:
 * [print(x) bytecode]
 * IINC x, 1
 * GOTO startLabel
 * endLabel:
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>No stack change (unconditional jump)</li>
 * </ul>
 *
 * @throws CompileException if continue is used outside a loop
 * @see com.elminster.jcp.eval.control.ContinueEvaluator
 */
public class ContinueCompiler extends AbstractAstCompiler {

    public ContinueCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        LoopLabels loop = ctx.currentLoop();
        if (loop == null) {
            throw new CompileException("continue statement outside of loop", getSourceLocation());
        }

        // Jump to the start of the loop
        mv.visitJumpInsn(Opcodes.GOTO, loop.getStartLabel());
    }
    @Override
    public DataType resolveType(CompileContext ctx) {
        return SystemDataType.VOID;  // Statements don't produce values
    }

}
