package com.elminster.jcp.compile.control;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.Statement;
import com.elminster.jcp.ast.statement.control.IfElseStatement;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for if-else conditional statements.
 *
 * <p>Generates bytecode for conditional branching with optional else clause.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>If-Else Statement:</h4>
 * <pre>{@code
 * // For: if (condition) { ifBody } else { elseBody }
 *
 * [compile condition]          // push boolean condition
 * IFEQ elseLabel               // if false (0), jump to else branch
 * [compile ifBody]             // execute if-body
 * GOTO endLabel                // skip else branch
 * elseLabel:
 * [compile elseBody]           // execute else-body
 * endLabel:
 * }</pre>
 *
 * <h4>If Without Else:</h4>
 * <pre>{@code
 * // For: if (condition) { ifBody }
 *
 * [compile condition]          // push boolean condition
 * IFEQ endLabel                // if false (0), skip if-body
 * [compile ifBody]             // execute if-body
 * GOTO endLabel                // (optimization: could be removed)
 * elseLabel:                   // empty else (just a label)
 * endLabel:
 * }</pre>
 *
 * <h4>Example: if (x > 5) { y = 1; } else { y = 0; }</h4>
 * <pre>{@code
 * ILOAD x                      // load x
 * ICONST_5                     // push 5
 * IF_ICMPGT condTrue           // if x > 5, jump to condTrue
 * ICONST_0                     // push false
 * GOTO condEnd
 * condTrue:
 * ICONST_1                     // push true
 * condEnd:
 * IFEQ elseLabel               // if condition false, go to else
 * ICONST_1                     // y = 1
 * ISTORE y
 * GOTO endLabel
 * elseLabel:
 * ICONST_0                     // y = 0
 * ISTORE y
 * endLabel:
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [...] (no change)</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.control.IfelseEvaluator
 */
public class IfelseCompiler extends ControlCompiler {

    public IfelseCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        emitLineNumber(mv);
        IfElseStatement ifElseStmt = (IfElseStatement) astNode;
        Expression condition = ifElseStmt.getCondition();
        Statement ifStatement = ifElseStmt.getIfStatement();
        Statement elseStatement = ifElseStmt.getElseStatement();

        Label elseLabel = new Label();
        Label endLabel = new Label();

        // Compile the condition (pushes boolean onto stack)
        Compilable condCompiler = AstCompilerFactory.getCompiler(condition);
        condCompiler.compile(mv, ctx);

        // If condition is false (0), jump to else branch
        mv.visitJumpInsn(Opcodes.IFEQ, elseLabel);

        // Compile the 'if' branch
        Compilable ifCompiler = AstCompilerFactory.getCompiler(ifStatement);
        ifCompiler.compile(mv, ctx);

        // Jump over the else branch
        mv.visitJumpInsn(Opcodes.GOTO, endLabel);

        // Else branch
        mv.visitLabel(elseLabel);
        if (elseStatement != null) {
            Compilable elseCompiler = AstCompilerFactory.getCompiler(elseStatement);
            elseCompiler.compile(mv, ctx);
        }

        mv.visitLabel(endLabel);
    }

}
