package com.elminster.jcp.compile.control;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.statement.control.ReturnStatement;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.exception.CompileException;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for return statements in functions.
 *
 * <p>Generates bytecode to return a value from a function. The appropriate
 * return opcode is selected based on the function's declared return type.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>Return with Value:</h4>
 * <pre>{@code
 * // For: return expr;
 *
 * [compile expr]       // push return value onto stack
 * IRETURN              // for int/boolean return type
 * // or
 * DRETURN              // for double return type
 * // or
 * ARETURN              // for reference types (String, Object, struct)
 * }</pre>
 *
 * <h4>Void Return:</h4>
 * <pre>{@code
 * // For: return;
 * RETURN               // return void (no value)
 * }</pre>
 *
 * <h4>Example: return x + y;</h4>
 * <pre>{@code
 * ILOAD x              // load x
 * ILOAD y              // load y
 * IADD                 // compute x + y
 * IRETURN              // return integer result
 * }</pre>
 *
 * <h4>Return Opcodes by Type:</h4>
 * <table>
 *   <tr><th>Type</th><th>Opcode</th></tr>
 *   <tr><td>int, boolean</td><td>IRETURN</td></tr>
 *   <tr><td>double</td><td>DRETURN</td></tr>
 *   <tr><td>String, Object, struct</td><td>ARETURN</td></tr>
 *   <tr><td>void</td><td>RETURN</td></tr>
 * </table>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [..., return_value] (if non-void)</li>
 *   <li>After: (method terminates)</li>
 * </ul>
 *
 * @throws CompileException if void function returns a value, or non-void function
 *         doesn't return a value, or return appears outside function context
 * @see com.elminster.jcp.eval.control.ReturnEvaluator
 */
public class ReturnCompiler extends AbstractAstCompiler {

    public ReturnCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        emitLineNumber(mv);
        ReturnStatement returnStmt = (ReturnStatement) astNode;
        Expression returnExpr = returnStmt.getExpression();

        // Get declared return type from context
        DataType returnType = ctx.getCurrentFunctionReturnType();

        // Validate return type is set
        if (returnType == null) {
            throw new CompileException("Return statement outside function context", getSourceLocation());
        }

        // Validate void/non-void consistency
        if (returnType == SystemDataType.VOID && returnExpr != null) {
            throw new CompileException("Void function cannot return a value", getSourceLocation());
        }
        if (returnType != SystemDataType.VOID && returnExpr == null) {
            throw new CompileException("Non-void function must return a value", getSourceLocation());
        }

        if (returnExpr != null) {
            // Compile the return expression
            Compilable exprCompiler = AstCompilerFactory.getCompiler(returnExpr);
            exprCompiler.compile(mv, ctx);

            // Emit correct return instruction based on return type
            int returnOpcode = TypeMapper.getReturnOpcode(returnType);
            mv.visitInsn(returnOpcode);
        } else {
            // Return void
            mv.visitInsn(Opcodes.RETURN);
        }
    }
}
