package com.elminster.jcp.compile.control;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.Statement;
import com.elminster.jcp.ast.statement.control.WhileStatement;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for while loop statements.
 *
 * <p>Generates bytecode for a while loop with proper break/continue support.
 * Pushes loop labels onto the context for nested break/continue statements.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: while (condition) { body }
 *
 * startLabel:                  // loop start (continue target)
 * [compile condition]          // push boolean condition
 * IFEQ endLabel                // if false (0), exit loop
 * [compile body]               // execute loop body
 * GOTO startLabel              // jump back to loop start
 * endLabel:                    // loop end (break target)
 * }</pre>
 *
 * <h4>Example: while (x > 0) { x--; }</h4>
 * <pre>{@code
 * startLabel:
 * ILOAD x                      // load x
 * ICONST_0                     // push 0
 * IF_ICMPGT condTrue           // if x > 0, jump to condTrue
 * ICONST_0                     // push false
 * GOTO condEnd
 * condTrue:
 * ICONST_1                     // push true
 * condEnd:
 * IFEQ endLabel                // if condition false, exit
 * ILOAD x                      // load x for decrement
 * IINC x, -1                   // decrement x
 * GOTO startLabel              // repeat loop
 * endLabel:
 * }</pre>
 *
 * <h4>Break/Continue Support:</h4>
 * <ul>
 *   <li>break: GOTO endLabel (exit loop)</li>
 *   <li>continue: GOTO startLabel (restart loop condition)</li>
 * </ul>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [...] (no change)</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.control.WhileEvaluator
 */
public class WhileCompiler extends AbstractAstCompiler {

    public WhileCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        emitLineNumber(mv);
        WhileStatement whileStmt = (WhileStatement) astNode;
        Expression condition = whileStmt.getConditionExpression();
        Statement body = whileStmt.getBody();

        Label startLabel = new Label();
        Label endLabel = new Label();

        // Push loop labels for break/continue support
        ctx.pushLoop(startLabel, endLabel);

        // Loop start
        mv.visitLabel(startLabel);

        // Compile condition
        Compilable condCompiler = AstCompilerFactory.getCompiler(condition);
        condCompiler.compile(mv, ctx);

        // If condition is false (0), exit loop
        mv.visitJumpInsn(Opcodes.IFEQ, endLabel);

        // Compile loop body
        Compilable bodyCompiler = AstCompilerFactory.getCompiler(body);
        bodyCompiler.compile(mv, ctx);

        // Jump back to loop start
        mv.visitJumpInsn(Opcodes.GOTO, startLabel);

        // Loop end
        mv.visitLabel(endLabel);

        // Pop loop labels
        ctx.popLoop();
    }
}
