package com.elminster.jcp.compile.operator.relational;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.BinaryExpression;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Base compiler for binary comparison expressions.
 *
 * <p>Provides common logic for compiling comparison operations (==, !=, &lt;, &gt;, &lt;=, &gt;=).
 * Handles type promotion (int to double) when operands have mixed types.
 * Generates conditional jump patterns to produce boolean results (0 or 1).
 *
 * <h3>Generated Bytecode Pattern:</h3>
 *
 * <h4>Integer Comparison:</h4>
 * <pre>{@code
 * [compile left operand]     // push left value
 * [compile right operand]    // push right value
 * IF_ICMPxx trueLabel        // conditional jump (e.g., IF_ICMPEQ, IF_ICMPLT)
 * ICONST_0                   // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1                   // push true
 * endLabel:
 * }</pre>
 *
 * <h4>Double Comparison:</h4>
 * <pre>{@code
 * [compile left operand]     // push left value
 * I2D                        // promote if int
 * [compile right operand]    // push right value
 * I2D                        // promote if int
 * DCMPL or DCMPG             // compare doubles (-1, 0, or 1)
 * IFxx trueLabel             // conditional jump (e.g., IFEQ, IFLT, IFGT)
 * ICONST_0                   // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1                   // push true
 * endLabel:
 * }</pre>
 *
 * <h4>DCMPL vs DCMPG:</h4>
 * <ul>
 *   <li>DCMPL: NaN produces -1 (use for &lt;, &lt;=, ==, !=)</li>
 *   <li>DCMPG: NaN produces +1 (use for &gt;, &gt;=)</li>
 * </ul>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., 0 or 1] (boolean result as int)</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.relational.CompareEvaluator
 */
public abstract class CompareCompiler extends AbstractAstCompiler {

    protected boolean useDouble;

    public CompareCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        BinaryExpression binaryExpr = (BinaryExpression) astNode;
        Expression left = binaryExpr.getLeft();
        Expression right = binaryExpr.getRight();

        DataType leftType = TypeMapper.getExpressionType(left, ctx);
        DataType rightType = TypeMapper.getExpressionType(right, ctx);
        useDouble = (leftType == SystemDataType.DOUBLE || rightType == SystemDataType.DOUBLE);

        // Compile left operand
        Compilable leftCompiler = AstCompilerFactory.getCompiler(left);
        leftCompiler.compile(mv, ctx);
        // Promote int to double if needed
        if (useDouble && leftType == SystemDataType.INT) {
            mv.visitInsn(Opcodes.I2D);
        }

        // Compile right operand
        Compilable rightCompiler = AstCompilerFactory.getCompiler(right);
        rightCompiler.compile(mv, ctx);
        // Promote int to double if needed
        if (useDouble && rightType == SystemDataType.INT) {
            mv.visitInsn(Opcodes.I2D);
        }

        // Generate comparison code
        Label trueLabel = new Label();
        Label endLabel = new Label();

        if (useDouble) {
            // For doubles: use DCMPL or DCMPG then conditional branch
            mv.visitInsn(getDoubleCompareOpcode());
            mv.visitJumpInsn(getDoubleConditionOpcode(), trueLabel);
        } else {
            // For integers: use IF_ICMPxx directly
            mv.visitJumpInsn(getCompareOpcode(), trueLabel);
        }

        // Push false (condition was false)
        mv.visitInsn(Opcodes.ICONST_0);
        mv.visitJumpInsn(Opcodes.GOTO, endLabel);

        // Push true (condition was true)
        mv.visitLabel(trueLabel);
        mv.visitInsn(Opcodes.ICONST_1);

        mv.visitLabel(endLabel);
    }

    /**
     * Get the integer comparison opcode (IF_ICMPEQ, IF_ICMPNE, IF_ICMPLT, etc.)
     *
     * @return the comparison opcode
     */
    protected abstract int getCompareOpcode();

    /**
     * Get the double compare opcode (DCMPL or DCMPG).
     * DCMPL: NaN → -1 (use for <, <=, ==, !=)
     * DCMPG: NaN → +1 (use for >, >=)
     *
     * @return DCMPL or DCMPG
     */
    protected int getDoubleCompareOpcode() {
        return Opcodes.DCMPL;
    }

    /**
     * Get the condition opcode for double comparison result.
     * After DCMPL/DCMPG, stack has -1, 0, or 1.
     *
     * @return IFLT, IFLE, IFGT, IFGE, IFEQ, or IFNE
     */
    protected abstract int getDoubleConditionOpcode();

    @Override
    public DataType resolveType(CompileContext ctx) {
        return SystemDataType.BOOLEAN;
    }
}
