package com.elminster.jcp.compile.operator.relational;

import com.elminster.jcp.ast.Node;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for greater than (&gt;) expressions.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>Integer Comparison:</h4>
 * <pre>{@code
 * // For: a > b (integers)
 * [compile a]          // push left operand
 * [compile b]          // push right operand
 * IF_ICMPGT trueLabel  // jump if greater than
 * ICONST_0             // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1             // push true
 * endLabel:
 * }</pre>
 *
 * <h4>Double Comparison:</h4>
 * <pre>{@code
 * // For: a > b (doubles)
 * [compile a]          // push left operand
 * [compile b]          // push right operand
 * DCMPG                // compare: -1 if a<b, 0 if a==b, 1 if a>b (NaN -> +1)
 * IFGT trueLabel       // jump if comparison result > 0
 * ICONST_0             // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1             // push true
 * endLabel:
 * }</pre>
 *
 * <h4>Note:</h4>
 * <p>Uses DCMPG (not DCMPL) so that NaN comparisons produce +1, causing the
 * greater-than test to fail correctly (NaN is not greater than anything).
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., 0 or 1]</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.relational.GreaterThanEvaluator
 */
public class GreaterThanCompiler extends CompareCompiler {

    public GreaterThanCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    protected int getCompareOpcode() {
        return Opcodes.IF_ICMPGT;
    }

    @Override
    protected int getDoubleCompareOpcode() {
        return Opcodes.DCMPG;  // Use DCMPG for > so NaN returns +1 (not greater)
    }

    @Override
    protected int getDoubleConditionOpcode() {
        return Opcodes.IFGT;  // DCMPG result > 0 means left > right
    }
}
