package com.elminster.jcp.compile.operator.relational;

import com.elminster.jcp.ast.Node;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for greater than or equal (&gt;=) expressions.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>Integer Comparison:</h4>
 * <pre>{@code
 * // For: a >= b (integers)
 * [compile a]          // push left operand
 * [compile b]          // push right operand
 * IF_ICMPGE trueLabel  // jump if greater than or equal
 * ICONST_0             // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1             // push true
 * endLabel:
 * }</pre>
 *
 * <h4>Double Comparison:</h4>
 * <pre>{@code
 * // For: a >= b (doubles)
 * [compile a]          // push left operand
 * [compile b]          // push right operand
 * DCMPG                // compare: -1 if a<b, 0 if a==b, 1 if a>b (NaN -> +1)
 * IFGE trueLabel       // jump if comparison result >= 0
 * ICONST_0             // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1             // push true
 * endLabel:
 * }</pre>
 *
 * <h4>Note:</h4>
 * <p>Uses DCMPG (not DCMPL) so that NaN comparisons produce +1, causing the
 * greater-or-equal test to fail correctly (NaN is not &gt;= anything).
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., 0 or 1]</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.relational.GreaterThanOrEqualEvaluator
 */
public class GreaterThanOrEqualCompiler extends CompareCompiler {

    public GreaterThanOrEqualCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    protected int getCompareOpcode() {
        return Opcodes.IF_ICMPGE;
    }

    @Override
    protected int getDoubleCompareOpcode() {
        return Opcodes.DCMPG;  // Use DCMPG for >= so NaN returns +1 (not greater or equal)
    }

    @Override
    protected int getDoubleConditionOpcode() {
        return Opcodes.IFGE;  // DCMPG result >= 0 means left >= right
    }

}
