package com.elminster.jcp.compile.operator.relational;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for less than (&lt;) expressions.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>Integer Comparison:</h4>
 * <pre>{@code
 * // For: a < b (integers)
 * [compile a]          // push left operand
 * [compile b]          // push right operand
 * IF_ICMPLT trueLabel  // jump if less than
 * ICONST_0             // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1             // push true
 * endLabel:
 * }</pre>
 *
 * <h4>Double Comparison:</h4>
 * <pre>{@code
 * // For: a < b (doubles)
 * [compile a]          // push left operand
 * [compile b]          // push right operand
 * DCMPL                // compare: -1 if a<b, 0 if a==b, 1 if a>b
 * IFLT trueLabel       // jump if comparison result < 0
 * ICONST_0             // push false
 * GOTO endLabel
 * trueLabel:
 * ICONST_1             // push true
 * endLabel:
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., 0 or 1]</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.relational.LessThanEvaluator
 */
public class LessThanCompiler extends CompareCompiler {

    public LessThanCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    protected int getCompareOpcode() {
        return Opcodes.IF_ICMPLT;
    }

    @Override
    protected int getDoubleConditionOpcode() {
        return Opcodes.IFLT;  // DCMPL result < 0 means left < right
    }
    @Override
    public DataType resolveType(CompileContext ctx) {
        return SystemDataType.BOOLEAN;  // Comparison operators return boolean
    }

}
