package com.elminster.jcp.compile.struct;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.StructInstantiation;
import com.elminster.jcp.ast.statement.declaration.StructFieldDef;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.exception.CompileException;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.StructType;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.util.List;

/**
 * Compiler for struct/type instantiation expressions.
 *
 * <p>Generates bytecode to create a new instance of a user-defined struct or type.
 * Uses the standard JVM object allocation pattern: NEW, DUP, args, INVOKESPECIAL.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: Point(10, 20)
 *
 * NEW Point                         // allocate memory for Point instance
 * DUP                               // duplicate reference (one for constructor, one as result)
 * BIPUSH 10                         // push first field value
 * BIPUSH 20                         // push second field value
 * INVOKESPECIAL Point.<init>(II)V   // call constructor
 * // Result: Point instance reference left on stack
 * }</pre>
 *
 * <h4>Complex Field Values:</h4>
 * <pre>{@code
 * // For: Point(x + 1, y * 2)
 *
 * NEW Point
 * DUP
 * ILOAD x                           // compile first field expression
 * ICONST_1
 * IADD
 * ILOAD y                           // compile second field expression
 * ICONST_2
 * IMUL
 * INVOKESPECIAL Point.<init>(II)V
 * }</pre>
 *
 * <h4>Nested Struct Instantiation:</h4>
 * <pre>{@code
 * // For: Line(Point(0, 0), Point(10, 10))
 *
 * NEW Line
 * DUP
 * NEW Point                         // create first Point
 * DUP
 * ICONST_0
 * ICONST_0
 * INVOKESPECIAL Point.<init>(II)V
 * NEW Point                         // create second Point
 * DUP
 * BIPUSH 10
 * BIPUSH 10
 * INVOKESPECIAL Point.<init>(II)V
 * INVOKESPECIAL Line.<init>(LPoint;LPoint;)V
 * }</pre>
 *
 * <h4>Constructor Descriptor:</h4>
 * <p>Built dynamically from field types:
 * <ul>
 *   <li>int → I</li>
 *   <li>boolean → Z</li>
 *   <li>double → D</li>
 *   <li>String → Ljava/lang/String;</li>
 *   <li>StructType → LStructName;</li>
 * </ul>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., struct_instance]</li>
 * </ul>
 *
 * @throws IllegalArgumentException if struct type is unknown or field count mismatches
 */
public class StructInstantiationCompiler extends AbstractAstCompiler {

    public StructInstantiationCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        StructInstantiation structInst = (StructInstantiation) astNode;
        String structName = structInst.getStructType().getId();

        // Look up struct type to get field definitions
        StructType structType = (StructType) ctx.getDataType(structName);
        if (structType == null) {
            throw new IllegalArgumentException("Unknown struct type: " + structName);
        }

        List<StructFieldDef> fields = structType.getFields();
        List<Expression> fieldValueExprs = structInst.getFieldValues();

        // Validate field count
        if (fields.size() != fieldValueExprs.size()) {
            throw new IllegalArgumentException(
                String.format("Struct %s expects %d fields, but got %d",
                    structName, fields.size(), fieldValueExprs.size()));
        }

        // Emit NEW instruction
        mv.visitTypeInsn(Opcodes.NEW, structName);

        // Emit DUP to have reference for constructor call
        mv.visitInsn(Opcodes.DUP);

        // Compile each field value expression
        for (int i = 0; i < fields.size(); i++) {
            Expression valueExpr = fieldValueExprs.get(i);
            AstCompilerFactory.getCompiler(valueExpr).compile(mv, ctx);

            // TODO: Type checking - verify value type matches field type
            // This would require type inference at compile time
        }

        // Build constructor descriptor
        StringBuilder descriptor = new StringBuilder("(");
        for (StructFieldDef field : fields) {
            descriptor.append(TypeMapper.toDescriptor(field.getDataType()));
        }
        descriptor.append(")V");

        // Emit INVOKESPECIAL to call constructor
        mv.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            structName,
            "<init>",
            descriptor.toString(),
            false
        );

        // Result: struct instance reference is on the stack
    }

    @Override
    public com.elminster.jcp.eval.data.DataType resolveType(CompileContext ctx) {
        StructInstantiation structInst = (StructInstantiation) astNode;
        String structName = structInst.getStructType().getId();
        com.elminster.jcp.eval.data.DataType dataType = ctx.getDataType(structName);
        if (dataType == null) {
            throw new CompileException(String.format("undefined struct type: %s", structName));
        }
        return dataType;
    }
}
