package com.elminster.jcp.compile.struct;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for the 'this' keyword.
 *
 * <p>Loads the current object instance reference onto the stack. In the JVM,
 * 'this' is always stored in local variable slot 0 for instance methods
 * and constructors.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: this
 *
 * ALOAD 0                           // load 'this' reference from slot 0
 * }</pre>
 *
 * <h4>Usage in Field Access:</h4>
 * <pre>{@code
 * // For: this.x
 *
 * ALOAD 0                           // load 'this'
 * GETFIELD StructName.x I           // access field
 * }</pre>
 *
 * <h4>Usage in Field Assignment:</h4>
 * <pre>{@code
 * // For: this.x = 10
 *
 * ALOAD 0                           // load 'this'
 * BIPUSH 10                         // push value
 * PUTFIELD StructName.x I           // store in field
 * }</pre>
 *
 * <h4>Usage in Method Chaining:</h4>
 * <pre>{@code
 * // For: return this (fluent API)
 *
 * ALOAD 0                           // load 'this'
 * ARETURN                           // return the reference
 * }</pre>
 *
 * <h4>JVM Convention:</h4>
 * <ul>
 *   <li>Instance methods: slot 0 = this, slots 1+ = parameters</li>
 *   <li>Constructors: slot 0 = uninitialized this, slots 1+ = parameters</li>
 *   <li>Static methods: slot 0 = first parameter (no 'this')</li>
 * </ul>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., this_reference]</li>
 * </ul>
 */
public class ThisCompiler extends AbstractAstCompiler {

    public ThisCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        // 'this' is always local variable slot 0 in instance methods/constructors
        // This is a JVM convention - slot 0 holds the receiver reference
        mv.visitVarInsn(Opcodes.ALOAD, 0);
    }
}
