package com.elminster.jcp.compile.declare;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.Statement;
import com.elminster.jcp.ast.statement.declaration.FunctionDeclaration;
import com.elminster.jcp.ast.statement.function.ParameterDef;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for function declarations.
 *
 * <p>Uses a two-pass compilation strategy:
 * <ul>
 *   <li>Pass 1: {@code compile()} registers the function signature</li>
 *   <li>Pass 2: {@code compileBody()} generates the function body bytecode</li>
 * </ul>
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>Pass 1 (compile):</h4>
 * <p>No bytecode generated. Registers function signature in context for forward
 * references (enabling functions to call each other regardless of declaration order).
 *
 * <h4>Pass 2 (compileBody):</h4>
 * <pre>{@code
 * // For: func add(a: int, b: int): int { return a + b; }
 *
 * // Method signature: static int add(int, int)
 * // Parameters allocated as local variables:
 * //   a -> index 0
 * //   b -> index 1
 *
 * // Method body:
 * ILOAD 0              // load a
 * ILOAD 1              // load b
 * IADD                 // compute a + b
 * IRETURN              // return result
 * }</pre>
 *
 * <h4>Void Function:</h4>
 * <pre>{@code
 * // For: func greet(): void { print("hello"); }
 *
 * [compile print("hello")]
 * RETURN               // implicit void return added automatically
 * }</pre>
 *
 * <h4>Method Invocation:</h4>
 * <p>Generated functions are static methods on the compiled class, called via
 * {@code INVOKESTATIC ClassName.methodName(descriptor)}.
 *
 * <h4>Parameter Allocation:</h4>
 * <p>For static methods, parameters start at local variable index 0 (no 'this').
 * Each parameter occupies one slot, except doubles which occupy two.
 */
public class FunctionDeclarationCompiler extends AbstractAstCompiler {

    public FunctionDeclarationCompiler(Node astNode) {
        super(astNode);
    }

    /**
     * Register the function signature in the context.
     * Called during Pass 1 or when encountered in main method.
     * No bytecode is emitted to the main method.
     */
    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        FunctionDeclaration fd = (FunctionDeclaration) astNode;
        ctx.registerFunction(
            fd.getId().getId(),
            fd.getParameterDefines(),
            fd.getDataType()
        );
        // No bytecode emitted to main method's MethodVisitor
    }

    /**
     * Compile the function body statements.
     * Called by BytecodeGenerator.generateFunctionMethod() during Pass 2.
     *
     * @param mv      the MethodVisitor for this function's method
     * @param funcCtx the compilation context for this function (isolated locals)
     */
    public void compileBody(MethodVisitor mv, CompileContext funcCtx) {
        FunctionDeclaration fd = (FunctionDeclaration) astNode;

        // Allocate parameters as local variables (starting at index 0 for static methods)
        for (ParameterDef param : fd.getParameterDefines()) {
            funcCtx.allocateLocal(param.getId(), param.getDataType());
        }

        // Compile body statements
        for (Statement stmt : fd.getBody()) {
            Compilable compiler = AstCompilerFactory.getCompiler(stmt);
            compiler.compile(mv, funcCtx);
        }

        // Add implicit return for void functions
        if (fd.getDataType() == DataType.SystemDataType.VOID) {
            mv.visitInsn(Opcodes.RETURN);
        }
    }
    @Override
    public DataType resolveType(CompileContext ctx) {
        return SystemDataType.VOID;  // Statements don't produce values
    }

}
