package com.elminster.jcp.compile.declare;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Identifier;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.statement.declaration.VariableDeclaration;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for variable declarations.
 *
 * <p>Generates bytecode to allocate a local variable slot and optionally
 * initialize it with a value. Emits line number information for debugging.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>With Initializer:</h4>
 * <pre>{@code
 * // For: int x = 10;
 * BIPUSH 10           // push initial value
 * ISTORE index        // store in local variable slot
 *
 * // For: String s = "hello";
 * LDC "hello"         // push string constant
 * ASTORE index        // store in local variable slot
 *
 * // For: Point p = Point(1, 2);
 * [struct instantiation bytecode]
 * ASTORE index        // store reference
 * }</pre>
 *
 * <h4>Without Initializer (default values):</h4>
 * <pre>{@code
 * // For: int x;
 * ICONST_0            // push default 0
 * ISTORE index
 *
 * // For: boolean b;
 * ICONST_0            // push default false
 * ISTORE index
 *
 * // For: String s;
 * LDC ""              // push empty string
 * ASTORE index
 *
 * // For: Object o;
 * ACONST_NULL         // push null
 * ASTORE index
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [...] (no change - value stored in local)</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.declare.VariableDeclarationEvaluator
 */
public class VariableDeclarationCompiler extends AbstractAstCompiler {

    public VariableDeclarationCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        emitLineNumber(mv);
        VariableDeclaration varDecl = (VariableDeclaration) astNode;
        Identifier id = varDecl.getId();
        String varName = id.getId();

        // Get the data type
        DataType dataType = resolveDataType(varDecl.getDataType().getName(), ctx);

        // Allocate a local variable slot
        int localIndex = ctx.allocateLocal(varName, dataType);

        // If there's an initializer, compile it
        Expression initExpr = varDecl.getInit();
        if (initExpr != null) {
            // Compile the initializer expression (pushes value onto stack)
            Compilable compilable = AstCompilerFactory.getCompiler(initExpr);
            compilable.compile(mv, ctx);

            // Store the value in the local variable
            int storeOpcode = TypeMapper.getStoreOpcode(dataType);
            mv.visitVarInsn(storeOpcode, localIndex);
        } else {
            // Initialize with default value
            compileDefaultValue(dataType, mv);
            int storeOpcode = TypeMapper.getStoreOpcode(dataType);
            mv.visitVarInsn(storeOpcode, localIndex);
        }
    }

    private DataType resolveDataType(String typeName, CompileContext ctx) {
        // Try to match system data types
        for (SystemDataType sdt : SystemDataType.values()) {
            if (sdt.getName().equalsIgnoreCase(typeName)) {
                return sdt;
            }
        }

        // Try to look up custom types (like structs) from context
        DataType customType = ctx.getDataType(typeName);
        if (customType != null) {
            return customType;
        }

        // Default to ANY
        return SystemDataType.ANY;
    }

    private void compileDefaultValue(DataType type, MethodVisitor mv) {
        if (type == SystemDataType.INT) {
            mv.visitInsn(Opcodes.ICONST_0);
        } else if (type == SystemDataType.BOOLEAN) {
            mv.visitInsn(Opcodes.ICONST_0);
        } else if (type == SystemDataType.STRING) {
            mv.visitLdcInsn("");
        } else {
            // For reference types, push null
            mv.visitInsn(Opcodes.ACONST_NULL);
        }
    }
}
