package com.elminster.jcp.compile.operator.arithmetic;

import com.elminster.jcp.ast.Node;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for division expressions (/).
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: a / b (integers)
 * [compile a]    // push left operand
 * [compile b]    // push right operand
 * IDIV           // integer division (truncates toward zero)
 *
 * // For: a / b (doubles or mixed)
 * [compile a]    // push left operand
 * I2D            // promote if int
 * [compile b]    // push right operand
 * I2D            // promote if int
 * DDIV           // double division
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., result]</li>
 * </ul>
 *
 * <h4>Note:</h4>
 * <p>Integer division by zero throws {@code ArithmeticException} at runtime.
 * Double division by zero produces {@code Infinity} or {@code NaN}.
 *
 * @see com.elminster.jcp.eval.operator.arithmetic.DivideEvaluator
 */
public class DivideCompiler extends ArithmeticCompiler {

    public DivideCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    protected void emitOperation(MethodVisitor mv) {
        mv.visitInsn(useDouble ? Opcodes.DDIV : Opcodes.IDIV);
    }
}
