package com.elminster.jcp.compile.operator.arithmetic;

import com.elminster.jcp.ast.Node;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for modulo (remainder) expressions (%).
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: a % b (integers)
 * [compile a]    // push left operand
 * [compile b]    // push right operand
 * IREM           // integer remainder
 *
 * // For: a % b (doubles or mixed)
 * [compile a]    // push left operand
 * I2D            // promote if int
 * [compile b]    // push right operand
 * I2D            // promote if int
 * DREM           // double remainder (IEEE 754)
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., result]</li>
 * </ul>
 *
 * <h4>Note:</h4>
 * <p>Integer modulo by zero throws {@code ArithmeticException} at runtime.
 *
 * @see com.elminster.jcp.eval.operator.arithmetic.ModEvaluator
 */
public class ModCompiler extends ArithmeticCompiler {

    public ModCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    protected void emitOperation(MethodVisitor mv) {
        mv.visitInsn(useDouble ? Opcodes.DREM : Opcodes.IREM);
    }
}
