package com.elminster.jcp.compile.operator.arithmetic;

import com.elminster.jcp.ast.Node;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for addition expressions (+).
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: a + b (integers)
 * [compile a]    // push left operand
 * [compile b]    // push right operand
 * IADD           // integer addition
 *
 * // For: a + b (doubles or mixed)
 * [compile a]    // push left operand
 * I2D            // promote if int
 * [compile b]    // push right operand
 * I2D            // promote if int
 * DADD           // double addition
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., result]</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.arithmetic.PlusEvaluator
 */
public class PlusCompiler extends ArithmeticCompiler {

    public PlusCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    protected void emitOperation(MethodVisitor mv) {
        mv.visitInsn(useDouble ? Opcodes.DADD : Opcodes.IADD);
    }
}
