package com.elminster.jcp.compile.operator.postfix;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Identifier;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.UnaryExpression;
import com.elminster.jcp.ast.expression.base.VariableExpression;
import com.elminster.jcp.ast.expression.operation.IdentifierExpression;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.context.CompileContext.LocalVariable;
import com.elminster.jcp.compile.exception.CompileException;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for post-increment (x++) expressions.
 *
 * <p>Generates bytecode to increment an integer variable while returning
 * the original (pre-increment) value. Uses the efficient {@code IINC}
 * instruction for the increment.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: x++
 *
 * ILOAD index          // load current value (return value)
 * IINC index, 1        // increment variable by 1
 * }</pre>
 *
 * <h4>Example: y = x++</h4>
 * <pre>{@code
 * // If x is at index 1, y is at index 2
 * ILOAD 1              // load x's current value (before increment)
 * IINC 1, 1            // increment x by 1 (in-place)
 * ISTORE 2             // store old value in y
 * }</pre>
 *
 * <h4>Note:</h4>
 * <p>Post-increment returns the value <i>before</i> the increment, which is
 * why we load first, then increment. The {@code IINC} instruction directly
 * modifies the local variable without using the stack.
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., old_value]</li>
 * </ul>
 *
 * @throws CompileException if the variable is not defined or is not an integer
 */
public class PlusPlusCompiler extends AbstractAstCompiler {

    public PlusPlusCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        UnaryExpression unaryExpr = (UnaryExpression) astNode;
        Expression operand = unaryExpr.getExpress();

        String varName = extractVariableName(operand);
        LocalVariable local = ctx.getLocal(varName);
        if (local == null) {
            throw new CompileException("Undefined variable: " + varName);
        }

        // Load current value (this is the return value for post-increment)
        mv.visitVarInsn(Opcodes.ILOAD, local.getIndex());

        // Increment the variable
        mv.visitIincInsn(local.getIndex(), 1);
    }

    private String extractVariableName(Expression expr) {
        if (expr instanceof VariableExpression) {
            Identifier id = ((VariableExpression) expr).getId();
            return id.getId();
        }
        if (expr instanceof IdentifierExpression) {
            return ((IdentifierExpression) expr).getId();
        }
        throw new CompileException("Invalid increment target: " + expr.getClass().getSimpleName());
    }

    @Override
    public com.elminster.jcp.eval.data.DataType resolveType(CompileContext ctx) {
        return com.elminster.jcp.eval.data.DataType.SystemDataType.INT;
    }
}
