package com.elminster.jcp.compile.operator.assignment;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Identifier;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.operation.AssignmentExpression;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import com.elminster.jcp.compile.context.CompileContext.LocalVariable;
import com.elminster.jcp.compile.exception.CompileException;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.TypeMapper;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for assignment expressions (=).
 *
 * <p>Generates bytecode to evaluate the right-hand side expression and store
 * the result in a local variable slot. Emits line number for debugging.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: x = expr;
 *
 * [compile expr]       // push value to assign
 * ISTORE index         // store in local (for int/boolean)
 * // or
 * DSTORE index         // store in local (for double)
 * // or
 * ASTORE index         // store in local (for reference types)
 * }</pre>
 *
 * <h4>Example: x = a + b</h4>
 * <pre>{@code
 * ILOAD a              // load a
 * ILOAD b              // load b
 * IADD                 // compute a + b
 * ISTORE x             // store result in x
 * }</pre>
 *
 * <h4>Store Opcodes by Type:</h4>
 * <table>
 *   <tr><th>Type</th><th>Opcode</th></tr>
 *   <tr><td>int, boolean</td><td>ISTORE</td></tr>
 *   <tr><td>double</td><td>DSTORE</td></tr>
 *   <tr><td>String, Object, struct</td><td>ASTORE</td></tr>
 * </table>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [...] (value stored in local variable, not left on stack)</li>
 * </ul>
 *
 * @throws CompileException if the variable is not defined in the current scope
 */
public class AssignmentCompiler extends AbstractAstCompiler {

    public AssignmentCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        emitLineNumber(mv);
        AssignmentExpression assignExpr = (AssignmentExpression) astNode;
        Identifier id = assignExpr.getId();
        Expression valueExpr = assignExpr.getExpression();

        // Get the variable name
        String varName = id.getId();
        LocalVariable local = ctx.getLocal(varName);
        if (local == null) {
            throw new CompileException("Undefined variable: " + varName, getSourceLocation());
        }

        // Compile the right-hand side expression
        Compilable rightCompiler = AstCompilerFactory.getCompiler(valueExpr);
        rightCompiler.compile(mv, ctx);

        // Store into the variable
        int storeOpcode = TypeMapper.getStoreOpcode(local.getType());
        mv.visitVarInsn(storeOpcode, local.getIndex());
    }
    @Override
    public DataType resolveType(CompileContext ctx) {
        return SystemDataType.VOID;  // Statements don't produce values
    }

}
