package com.elminster.jcp.compile.function;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.base.FunctionCallExpression;
import com.elminster.jcp.ast.statement.function.ParameterDef;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.context.CompileContext.FunctionSignature;
import com.elminster.jcp.compile.exception.CompileException;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.CompileModeClassConverter;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import com.elminster.jcp.eval.data.ExternalClassType;
import com.elminster.jcp.eval.data.ExternalMethodDef;
import com.elminster.jcp.eval.data.TypePromotion;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.util.Arrays;
import org.objectweb.asm.Type;

/**
 * Compiler for function call expressions.
 *
 * <p>Generates bytecode to call user-defined functions (as static methods) or
 * external Java class constructors. Handles argument type promotion and boxing.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>User-Defined Function Call:</h4>
 * <pre>{@code
 * // For: add(x, y)
 *
 * [compile arg1]                       // push first argument
 * [compile arg2]                       // push second argument
 * INVOKESTATIC ClassName.add(II)I      // call static method
 * // Result (if non-void) left on stack
 * }</pre>
 *
 * <h4>Type Promotion:</h4>
 * <pre>{@code
 * // For: doubleFunc(intValue)
 *
 * ILOAD intValue       // load int argument
 * I2D                  // promote int to double
 * INVOKESTATIC ClassName.doubleFunc(D)D
 * }</pre>
 *
 * <h4>External Class Constructor (TypeName.new):</h4>
 * <pre>{@code
 * // For: StringBuilder.new("hello")
 *
 * NEW java/lang/StringBuilder          // allocate instance
 * DUP                                  // duplicate reference
 * LDC "hello"                          // push constructor argument
 * INVOKESPECIAL StringBuilder.<init>(Ljava/lang/String;)V
 * // Result: StringBuilder instance reference on stack
 * }</pre>
 *
 * <h4>Boxing for Object Parameters:</h4>
 * <pre>{@code
 * // For: methodTakingObject(intValue)
 *
 * ILOAD intValue
 * INVOKESTATIC Integer.valueOf(I)Ljava/lang/Integer;  // box int -> Integer
 * INVOKESTATIC ClassName.method(Ljava/lang/Object;)V
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., return_value] (if non-void)</li>
 *   <li>After: [...] (if void)</li>
 * </ul>
 *
 * @throws CompileException if function is not defined or argument types don't match
 */
public class FunCallCompiler extends AbstractAstCompiler {

    /** Base package for JCP base module classes */
    private static final String BASE_MODULE_PACKAGE = "com.elminster.jcp.module.base";

    public FunCallCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        emitLineNumber(mv);
        FunctionCallExpression call = (FunctionCallExpression) astNode;
        String funcName = call.getId().getId();
        Expression[] args = call.getArguments();

        // Check if this is an external class constructor call (TypeName.new)
        if (funcName.endsWith(".new")) {
            String typeName = funcName.substring(0, funcName.length() - 4);
            DataType dataType = ctx.getDataType(typeName);
            if (dataType instanceof ExternalClassType) {
                compileExternalClassConstructor(mv, ctx, (ExternalClassType) dataType, args);
                return;
            }
        }

        // Check if this is a module function call
        // Valid patterns: "Type.method" or "module::Type.method"
        // Must contain "." and if contains "::" it must be before the "."
        if (isModuleFunctionPattern(funcName)) {
            // Try to compile as module function call
            try {
                compileModuleFunctionCall(mv, ctx, funcName, args);
                return;
            } catch (ClassNotFoundException e) {
                // Module class not found - not a module function
                // Fall through to user-defined function lookup below
                // (which will provide appropriate error if that also fails)
            } catch (NoSuchMethodException e) {
                // Module class exists but method not found - throw clear error
                throw new CompileException("Module function not found: " + funcName +
                    " - " + e.getMessage(), getSourceLocation());
            } catch (Exception e) {
                // Other reflection errors during module function call - rethrow
                throw new CompileException("Error compiling module function: " + funcName +
                    " - " + e.getMessage(), getSourceLocation());
            }
        }

        // Determine argument types for overload resolution
        DataType[] argTypes = new DataType[args.length];
        for (int i = 0; i < args.length; i++) {
            argTypes[i] = TypeMapper.getExpressionType(args[i], ctx);
        }

        // Lookup function signature
        FunctionSignature sig = ctx.lookupFunction(funcName, argTypes);
        if (sig == null) {
            throw new CompileException("Undefined function: " + funcName +
                " with argument types " + Arrays.toString(argTypes), getSourceLocation());
        }

        // Compile arguments (push values onto stack)
        ParameterDef[] params = sig.getParameters();
        for (int i = 0; i < args.length; i++) {
            Compilable argCompiler = AstCompilerFactory.getCompiler(args[i]);
            argCompiler.compile(mv, ctx);

            // Type promotion if needed (e.g., int to double)
            DataType argType = argTypes[i];
            DataType paramType = params[i].getDataType();
            int promotionOpcode = TypePromotion.getPromotionOpcode(argType, paramType);
            if (promotionOpcode != TypePromotion.NO_PROMOTION_OPCODE) {
                mv.visitInsn(promotionOpcode);
            }
        }

        // Emit INVOKESTATIC
        mv.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            ctx.getClassName(),
            funcName,
            sig.getDescriptor(),
            false
        );
        // Result (if any) is now on stack
    }

    /**
     * Check if function name matches a valid module function pattern.
     *
     * <p>Valid patterns:
     * <ul>
     *   <li>func - global function (base/user module, no module/type prefix)</li>
     *   <li>module::func - global function with explicit module</li>
     *   <li>Type.method - base/user module type method</li>
     *   <li>module::Type.method - explicit module type method</li>
     * </ul>
     *
     * <p>Invalid patterns:
     * <ul>
     *   <li>Type.method.invalid - multiple dots after module delimiter</li>
     *   <li>::func - empty module name</li>
     * </ul>
     *
     * @param funcName the function name to validate
     * @return true if it matches a valid module function pattern
     */
    private boolean isModuleFunctionPattern(String funcName) {
        // Check for :: delimiter
        if (funcName.contains("::")) {
            int moduleDelimiter = funcName.indexOf("::");
            // Module name must not be empty
            if (moduleDelimiter == 0) {
                return false;
            }
            // After :: can be:
            // - "func" (global function, no dot)
            // - "Type.method" (type method, exactly one dot)
            String afterModule = funcName.substring(moduleDelimiter + 2);
            int dotCount = afterModule.length() - afterModule.replace(".", "").length();
            return dotCount == 0 || dotCount == 1;
        } else {
            // Without ::, can be:
            // - "func" (global function, no dot)
            // - "Type.method" (type method, exactly one dot)
            int dotCount = funcName.length() - funcName.replace(".", "").length();
            return dotCount == 0 || dotCount == 1;
        }
    }

    /**
     * Compile module function call: module::Type.function(args), Type.function(args),
     * module::func(args), or func(args)
     *
     * <p>Syntax:
     * <ul>
     *   <li>Type method explicit: {@code base::Assertions.assertTrue(condition)}</li>
     *   <li>Type method shorthand: {@code Assertions.assertTrue(condition)} (omits "base::")</li>
     *   <li>Global function explicit: {@code base::abs(value)}</li>
     *   <li>Global function shorthand: {@code abs(value)} (omits "base::" and "global")</li>
     * </ul>
     *
     * <p>Module functions are static methods in Java classes from modules.
     *
     * @throws ClassNotFoundException if the module class cannot be found
     * @throws NoSuchMethodException if the method is not found in the module class
     */
    private void compileModuleFunctionCall(MethodVisitor mv, CompileContext ctx,
                                          String fullName, Expression[] args)
            throws ClassNotFoundException, NoSuchMethodException {
        // Parse module::Type.method, Type.method, module::func, or func
        String moduleName;
        String typeAndMethod;

        if (fullName.contains("::")) {
            // Explicit module: "base::Assertions.assertTrue" or "base::abs"
            int moduleDelimiter = fullName.indexOf("::");
            moduleName = fullName.substring(0, moduleDelimiter);
            typeAndMethod = fullName.substring(moduleDelimiter + 2);
        } else {
            // Shorthand: "Assertions.assertTrue" or "abs" means base module
            moduleName = null; // Will default to base module
            typeAndMethod = fullName;
        }

        // Determine if this is a type method or global function
        String typeName;
        String methodName;

        if (typeAndMethod.contains(".")) {
            // Type method: "Assertions.assertTrue"
            int dotIndex = typeAndMethod.lastIndexOf('.');
            typeName = typeAndMethod.substring(0, dotIndex);
            methodName = typeAndMethod.substring(dotIndex + 1);
        } else {
            // Global function: "abs" → type="global", method="abs"
            typeName = "global";
            methodName = typeAndMethod;
        }

        // Resolve to a Java Class — base module, then context-registered external class
        Class<?> clazz = resolveModuleClass(moduleName, typeName, ctx);
        String className = clazz.getName();

        // Determine argument types for descriptor
        DataType[] argTypes = new DataType[args.length];
        for (int i = 0; i < args.length; i++) {
            argTypes[i] = TypeMapper.getExpressionType(args[i], ctx);
        }

        // Discover the actual method via reflection — gives us the exact descriptor
        java.lang.reflect.Method resolvedMethod;
        DataType returnType;
        try {
            resolvedMethod = discoverMethod(clazz, methodName, argTypes);
            returnType = CompileModeClassConverter.mapJavaTypeToDataType(resolvedMethod.getReturnType());
        } catch (NoSuchMethodException e) {
            throw new CompileException("Module function not found: " + methodName +
                " with argument types " + Arrays.toString(argTypes) +
                " in class " + className, getSourceLocation());
        }

        // Compile arguments and emit boxing when the Java param type is Object/ANY
        Class<?>[] paramTypes = resolvedMethod.getParameterTypes();
        for (int i = 0; i < args.length; i++) {
            Compilable argCompiler = AstCompilerFactory.getCompiler(args[i]);
            argCompiler.compile(mv, ctx);

            DataType argType = argTypes[i];
            DataType paramDataType = CompileModeClassConverter.mapJavaTypeToDataType(paramTypes[i]);
            int promotionOpcode = TypePromotion.getPromotionOpcode(argType, paramDataType);
            if (promotionOpcode != TypePromotion.NO_PROMOTION_OPCODE) {
                mv.visitInsn(promotionOpcode);
            } else if (paramDataType == SystemDataType.ANY) {
                boxPrimitive(mv, argType);
            }
        }

        // Use exact JVM descriptor from reflection — never the lossy JCP-type-derived one
        String descriptor = Type.getMethodDescriptor(resolvedMethod);

        // Emit INVOKESTATIC
        String internalName = className.replace('.', '/');
        mv.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            internalName,
            methodName,
            descriptor,
            false
        );
    }

    /**
     * Resolve module and type name to a Java Class.
     *
     * <p>Resolution order:
     * <ol>
     *   <li>Base module package ({@code com.elminster.jcp.module.base.<type>.<Type>})</li>
     *   <li>Context-registered ExternalClassType (user-provided JARs)</li>
     * </ol>
     *
     * @param moduleName null for shorthand (defaults to base), or explicit module name
     * @param typeName   the type name (e.g., "Assertions", "StringUtils")
     * @param ctx        the current compile context
     * @return the resolved Class
     * @throws ClassNotFoundException if the class cannot be found anywhere
     */
    private Class<?> resolveModuleClass(String moduleName, String typeName, CompileContext ctx)
            throws ClassNotFoundException {
        if (moduleName != null && !"base".equals(moduleName)) {
            // Explicit non-base module — look only in context; no base-package fallback
            DataType dt = ctx.getDataType(typeName);
            if (dt instanceof ExternalClassType) {
                return ((ExternalClassType) dt).getJavaClass();
            }
            throw new ClassNotFoundException("Non-base module '" + moduleName + "::" + typeName +
                "' not found in compile context");
        }

        // Base module (explicit "base::" or shorthand): try base package first
        String packageName = typeName.toLowerCase();
        String baseModuleClass = BASE_MODULE_PACKAGE + "." + packageName + "." + typeName;
        try {
            return Class.forName(baseModuleClass);
        } catch (ClassNotFoundException ignored) {
            // fall through to context lookup
        }

        // Not in base module — check context-registered external class
        DataType dt = ctx.getDataType(typeName);
        if (dt instanceof ExternalClassType) {
            return ((ExternalClassType) dt).getJavaClass();
        }

        throw new ClassNotFoundException("Type '" + typeName +
            "' not found in base module or compile context: " + baseModuleClass);
    }

    /**
     * Discover the Java Method for a module function via reflection.
     * Matches method by name and compatible parameter types.
     *
     * @param clazz      the module class
     * @param methodName the method name
     * @param argTypes   the argument types
     * @return the matched Java Method
     * @throws NoSuchMethodException if no matching method found
     * @throws CompileException if multiple methods match (ambiguous)
     */
    private java.lang.reflect.Method discoverMethod(Class<?> clazz, String methodName, DataType[] argTypes)
            throws NoSuchMethodException {
        java.lang.reflect.Method[] methods = clazz.getDeclaredMethods();
        java.lang.reflect.Method matchedMethod = null;

        for (java.lang.reflect.Method method : methods) {
            if (!method.getName().equals(methodName)) {
                continue;
            }
            if (!java.lang.reflect.Modifier.isStatic(method.getModifiers())) {
                continue;
            }

            Class<?>[] paramTypes = method.getParameterTypes();
            if (paramTypes.length != argTypes.length) {
                continue;
            }

            boolean compatible = true;
            for (int i = 0; i < paramTypes.length; i++) {
                if (!isCompatibleType(argTypes[i], paramTypes[i])) {
                    compatible = false;
                    break;
                }
            }

            if (compatible) {
                if (matchedMethod != null) {
                    throw new CompileException("Ambiguous module function: " + methodName +
                        " in class " + clazz.getName(), getSourceLocation());
                }
                matchedMethod = method;
            }
        }

        if (matchedMethod == null) {
            throw new NoSuchMethodException("Module function not found: " + methodName +
                " with argument types " + Arrays.toString(argTypes) +
                " in class " + clazz.getName());
        }

        return matchedMethod;
    }

    /**
     * Check if a JCP DataType is compatible with a Java parameter type.
     *
     * <p>Uses existing utilities:
     * <ul>
     *   <li>{@link CompileModeClassConverter#mapJavaTypeToDataType} - Convert Java Class to DataType</li>
     *   <li>{@link DataType#isCompatibleWith} - Check DataType compatibility</li>
     * </ul>
     *
     * @param jcpType the JCP data type (argument type)
     * @param javaType the Java parameter type
     * @return true if compatible for method invocation
     */
    private boolean isCompatibleType(DataType jcpType, Class<?> javaType) {
        if (jcpType == null) {
            return false;  // Cannot determine compatibility if type is unknown
        }
        DataType paramDataType = CompileModeClassConverter.mapJavaTypeToDataType(javaType);
        return jcpType.isCompatibleWith(paramDataType);
    }


    /**
     * Compile external class constructor call: TypeName.new(args)
     */
    private void compileExternalClassConstructor(MethodVisitor mv, CompileContext ctx,
                                                  ExternalClassType extType, Expression[] args) {
        // Determine argument types for overload resolution
        DataType[] argTypes = new DataType[args.length];
        for (int i = 0; i < args.length; i++) {
            argTypes[i] = TypeMapper.getExpressionType(args[i], ctx);
        }

        // Look up constructor with overload resolution
        ExternalMethodDef constructor = extType.getConstructor(argTypes);
        if (constructor == null) {
            throw new CompileException("Constructor for '" + extType.getName() +
                "' with argument types " + Arrays.toString(argTypes) + " not found", getSourceLocation());
        }

        // Emit NEW instruction
        mv.visitTypeInsn(Opcodes.NEW, extType.getInternalName());

        // Emit DUP to have reference for constructor call
        mv.visitInsn(Opcodes.DUP);

        // Compile arguments (push values onto stack)
        DataType[] paramTypes = constructor.getParameterTypes();
        for (int i = 0; i < args.length; i++) {
            Compilable argCompiler = AstCompilerFactory.getCompiler(args[i]);
            argCompiler.compile(mv, ctx);

            // Type promotion and boxing
            DataType argType = argTypes[i];
            DataType paramType = paramTypes[i];
            int promotionOpcode = TypePromotion.getPromotionOpcode(argType, paramType);
            if (promotionOpcode != TypePromotion.NO_PROMOTION_OPCODE) {
                mv.visitInsn(promotionOpcode);
            } else if (paramType == SystemDataType.ANY) {
                boxPrimitive(mv, argType);
            }
        }

        // Emit INVOKESPECIAL to call constructor
        mv.visitMethodInsn(
            Opcodes.INVOKESPECIAL,
            extType.getInternalName(),
            "<init>",
            constructor.getDescriptor(),
            false
        );
        // Result: new instance reference is on the stack
    }

    /**
     * Box a primitive type to its wrapper class.
     */
    private void boxPrimitive(MethodVisitor mv, DataType type) {
        if (type == SystemDataType.INT) {
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Integer", "valueOf",
                "(I)Ljava/lang/Integer;", false);
        } else if (type == SystemDataType.BOOLEAN) {
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Boolean", "valueOf",
                "(Z)Ljava/lang/Boolean;", false);
        } else if (type == SystemDataType.DOUBLE) {
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Double", "valueOf",
                "(D)Ljava/lang/Double;", false);
        }
    }

    @Override
    public DataType resolveType(CompileContext ctx) {
        // Note: only resolves user-defined functions registered in the context.
        // Module function calls (e.g. Assertions.assertTrue) and external class
        // constructors (e.g. StringBuilder.new) are handled by compileModuleFunctionCall()
        // and compileExternalClassConstructor() in compile(), respectively.
        FunctionCallExpression call = (FunctionCallExpression) astNode;
        String funcName = call.getId().getId();
        Expression[] args = call.getArguments();

        DataType[] argTypes = new DataType[args.length];
        for (int i = 0; i < args.length; i++) {
            argTypes[i] = TypeMapper.getExpressionType(args[i], ctx);
        }

        FunctionSignature sig = ctx.lookupFunction(funcName, argTypes);
        if (sig == null) {
            throw new CompileException(String.format("undefined function: %s", funcName));
        }
        return sig.getReturnType();
    }
}
