package com.elminster.jcp.compile.function;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.base.MethodCallExpression;
import com.elminster.jcp.ast.statement.declaration.MethodDef;
import com.elminster.jcp.ast.statement.function.ParameterDef;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.exception.CompileException;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import com.elminster.jcp.eval.data.ExternalClassType;
import com.elminster.jcp.eval.data.ExternalMethodDef;
import com.elminster.jcp.eval.data.StructType;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.util.Arrays;

/**
 * Compiler for instance method calls: instance.method(args)
 *
 * <p>Generates bytecode to call methods on object instances (external Java classes
 * or user-defined struct types). The receiver object is compiled first, then
 * arguments, followed by INVOKEVIRTUAL.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>External Java Method Call:</h4>
 * <pre>{@code
 * // For: sb.append("hello")
 *
 * ALOAD sb                              // push receiver (StringBuilder instance)
 * LDC "hello"                           // push argument
 * INVOKEVIRTUAL StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
 * // Result: method return value on stack
 * }</pre>
 *
 * <h4>Struct Instance Method Call:</h4>
 * <pre>{@code
 * // For: point.distanceTo(otherPoint)
 *
 * ALOAD point                           // push receiver (Point instance)
 * ALOAD otherPoint                      // push argument
 * INVOKEVIRTUAL Point.distanceTo(LPoint;)D
 * // Result: double distance on stack
 * }</pre>
 *
 * <h4>Type Promotion:</h4>
 * <pre>{@code
 * // For: obj.methodTakingDouble(intValue)
 *
 * ALOAD obj                             // push receiver
 * ILOAD intValue                        // push int argument
 * I2D                                   // promote int to double
 * INVOKEVIRTUAL Type.method(D)V
 * }</pre>
 *
 * <h4>Boxing for Object Parameters:</h4>
 * <pre>{@code
 * // For: list.add(intValue) where add takes Object
 *
 * ALOAD list                            // push receiver
 * ILOAD intValue                        // push int
 * INVOKESTATIC Integer.valueOf(I)Ljava/lang/Integer;  // box to Integer
 * INVOKEVIRTUAL ArrayList.add(Ljava/lang/Object;)Z
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., return_value] (if non-void)</li>
 *   <li>After: [...] (if void)</li>
 * </ul>
 *
 * @throws CompileException if method is not found on the target type
 */
public class MethodCallCompiler extends AbstractAstCompiler {

    public MethodCallCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        emitLineNumber(mv);
        MethodCallExpression call = (MethodCallExpression) astNode;
        String methodName = call.getMethodName();
        Expression targetExpr = call.getExpression();
        Expression[] args = call.getArguments();

        // 1. Compile target expression (push instance reference onto stack)
        Compilable targetCompiler = AstCompilerFactory.getCompiler(targetExpr);
        targetCompiler.compile(mv, ctx);

        // 2. Determine the type of the target
        DataType targetType = TypeMapper.getExpressionType(targetExpr, ctx);

        // 3. Determine argument types for overload resolution
        DataType[] argTypes = new DataType[args.length];
        for (int i = 0; i < args.length; i++) {
            argTypes[i] = TypeMapper.getExpressionType(args[i], ctx);
        }

        // 4. Handle different type kinds
        if (targetType instanceof ExternalClassType) {
            compileExternalClassCall(mv, ctx, (ExternalClassType) targetType, methodName, args, argTypes);
        } else if (targetType instanceof StructType) {
            compileStructTypeCall(mv, ctx, (StructType) targetType, methodName, args, argTypes);
        } else {
            throw new CompileException("Cannot call method on type: " + targetType);
        }
    }

    /**
     * Compile instance method call on ExternalClassType (external Java class).
     */
    private void compileExternalClassCall(MethodVisitor mv, CompileContext ctx,
                                          ExternalClassType extType, String methodName,
                                          Expression[] args, DataType[] argTypes) {
        // Look up instance method with overload resolution
        ExternalMethodDef method = extType.getInstanceMethod(methodName, argTypes);
        if (method == null) {
            throw new CompileException("Method '" + methodName +
                "' with argument types " + Arrays.toString(argTypes) +
                " not found in type '" + extType.getName() + "'");
        }

        // Compile arguments (push values onto stack)
        DataType[] paramTypes = method.getParameterTypes();
        for (int i = 0; i < args.length; i++) {
            Compilable argCompiler = AstCompilerFactory.getCompiler(args[i]);
            argCompiler.compile(mv, ctx);

            // Type promotion and boxing
            DataType argType = argTypes[i];
            DataType paramType = paramTypes[i];
            if (paramType == SystemDataType.DOUBLE && argType == SystemDataType.INT) {
                mv.visitInsn(Opcodes.I2D);
            } else if (paramType == SystemDataType.ANY) {
                // Box primitives when passing to Object parameter
                boxPrimitive(mv, argType);
            }
        }

        // Emit INVOKEINTERFACE for interfaces, INVOKEVIRTUAL for classes
        boolean isInterface = extType.getJavaClass().isInterface();
        mv.visitMethodInsn(
            isInterface ? Opcodes.INVOKEINTERFACE : Opcodes.INVOKEVIRTUAL,
            extType.getInternalName(),
            methodName,
            method.getDescriptor(),
            isInterface
        );
    }

    /**
     * Compile instance method call on StructType (user-defined type).
     */
    private void compileStructTypeCall(MethodVisitor mv, CompileContext ctx,
                                       StructType structType, String methodName,
                                       Expression[] args, DataType[] argTypes) {
        // Look up method with overload resolution (supports type hierarchy)
        MethodDef method = structType.getInstanceMethod(methodName, argTypes);
        if (method == null) {
            throw new CompileException("Method '" + methodName +
                "' with argument types " + Arrays.toString(argTypes) +
                " not found in type '" + structType.getName() + "'");
        }

        // Compile arguments (push values onto stack)
        ParameterDef[] params = method.getParameters();
        for (int i = 0; i < args.length; i++) {
            Compilable argCompiler = AstCompilerFactory.getCompiler(args[i]);
            argCompiler.compile(mv, ctx);

            // Type promotion if needed (int to double)
            DataType argType = argTypes[i];
            DataType paramType = params[i].getDataType();
            if (paramType == SystemDataType.DOUBLE && argType == SystemDataType.INT) {
                mv.visitInsn(Opcodes.I2D);
            }
        }

        // Build method descriptor
        String descriptor = buildMethodDescriptor(params, method.getReturnType());

        // Emit INVOKEVIRTUAL
        mv.visitMethodInsn(
            Opcodes.INVOKEVIRTUAL,
            structType.getName(),
            methodName,
            descriptor,
            false
        );
    }

    /**
     * Build method descriptor from parameters and return type.
     */
    private String buildMethodDescriptor(ParameterDef[] params, DataType returnType) {
        StringBuilder sb = new StringBuilder("(");
        if (params != null) {
            for (ParameterDef param : params) {
                sb.append(TypeMapper.toDescriptor(param.getDataType()));
            }
        }
        sb.append(")");
        sb.append(TypeMapper.toDescriptor(returnType));
        return sb.toString();
    }

    /**
     * Box a primitive type to its wrapper class.
     * INT -> Integer, BOOLEAN -> Boolean, DOUBLE -> Double
     */
    private void boxPrimitive(MethodVisitor mv, DataType type) {
        if (type == SystemDataType.INT) {
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Integer", "valueOf",
                "(I)Ljava/lang/Integer;", false);
        } else if (type == SystemDataType.BOOLEAN) {
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Boolean", "valueOf",
                "(Z)Ljava/lang/Boolean;", false);
        } else if (type == SystemDataType.DOUBLE) {
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/Double", "valueOf",
                "(D)Ljava/lang/Double;", false);
        }
        // String and Object types don't need boxing
    }

    @Override
    public DataType resolveType(CompileContext ctx) {
        MethodCallExpression call = (MethodCallExpression) astNode;
        String methodName = call.getMethodName();
        Expression targetExpr = call.getExpression();
        Expression[] args = call.getArguments();

        DataType targetType = TypeMapper.getExpressionType(targetExpr, ctx);
        DataType[] argTypes = new DataType[args.length];
        for (int i = 0; i < args.length; i++) {
            argTypes[i] = TypeMapper.getExpressionType(args[i], ctx);
        }

        if (targetType instanceof ExternalClassType) {
            ExternalMethodDef method = ((ExternalClassType) targetType).getInstanceMethod(methodName, argTypes);
            if (method == null) {
                throw new CompileException(String.format(
                    "undefined method '%s' on type '%s'", methodName, targetType));
            }
            return method.getReturnType();
        } else if (targetType instanceof StructType) {
            com.elminster.jcp.ast.statement.declaration.MethodDef method =
                ((StructType) targetType).getInstanceMethod(methodName, argTypes);
            if (method == null) {
                throw new CompileException(String.format(
                    "undefined method '%s' on type '%s'", methodName, targetType));
            }
            return method.getReturnType();
        }
        throw new CompileException(String.format(
            "cannot call method '%s' on non-object type: %s", methodName, targetType));
    }
}
