package com.elminster.jcp.compile.operator.logical;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.operation.LogicalAndExpression;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for logical AND expressions (&&).
 *
 * <p>Implements short-circuit evaluation: if left is false, right is not evaluated.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: left && right
 * [compile left]         // push left value (0 or 1)
 * IFEQ falseLabel        // if left is 0 (false), jump to falseLabel
 * [compile right]        // push right value (0 or 1)
 * IFEQ falseLabel        // if right is 0 (false), jump to falseLabel
 * ICONST_1               // both true: push 1 (true)
 * GOTO endLabel
 * falseLabel:
 * ICONST_0               // at least one false: push 0 (false)
 * endLabel:
 * }</pre>
 *
 * <h4>Short-Circuit Behavior:</h4>
 * <ul>
 *   <li>If left evaluates to false (0), jump directly to falseLabel without evaluating right</li>
 *   <li>Only evaluate right if left is true (1)</li>
 * </ul>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., 0 or 1] (boolean result as int)</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.logical.AndEvaluator
 */
public class AndCompiler extends AbstractAstCompiler {

    public AndCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        LogicalAndExpression andExpr = (LogicalAndExpression) astNode;
        Expression left = andExpr.getLeft();
        Expression right = andExpr.getRight();

        Label falseLabel = new Label();
        Label endLabel = new Label();

        // Compile left operand
        Compilable leftCompiler = AstCompilerFactory.getCompiler(left);
        leftCompiler.compile(mv, ctx);
        // Short-circuit: if left is false (0), skip right and return false
        mv.visitJumpInsn(Opcodes.IFEQ, falseLabel);

        // Left was true, now evaluate right
        Compilable rightCompiler = AstCompilerFactory.getCompiler(right);
        rightCompiler.compile(mv, ctx);
        // If right is false (0), jump to falseLabel
        mv.visitJumpInsn(Opcodes.IFEQ, falseLabel);

        // Both true: push 1
        mv.visitInsn(Opcodes.ICONST_1);
        mv.visitJumpInsn(Opcodes.GOTO, endLabel);

        // At least one false: push 0
        mv.visitLabel(falseLabel);
        mv.visitInsn(Opcodes.ICONST_0);

        mv.visitLabel(endLabel);
    }
    @Override
    public DataType resolveType(CompileContext ctx) {
        return SystemDataType.BOOLEAN;  // Logical operators always produce a boolean result
    }

}
