package com.elminster.jcp.compile.operator.logical;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.operation.LogicalNotExpression;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for logical NOT expressions (!).
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: !expression
 * [compile expression]  // push boolean value (0 or 1)
 * ICONST_1             // push 1
 * IXOR                 // XOR: flips 0→1, 1→0
 * }</pre>
 *
 * <h4>How IXOR Flips Booleans:</h4>
 * <ul>
 *   <li>false (0) XOR 1 = 1 (true)</li>
 *   <li>true (1) XOR 1 = 0 (false)</li>
 * </ul>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., result] (inverted boolean as 0 or 1)</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.logical.NotEvaluator
 */
public class NotCompiler extends AbstractAstCompiler {

    public NotCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        LogicalNotExpression notExpr = (LogicalNotExpression) astNode;
        Expression innerExpression = notExpr.getExpression();

        // Compile the inner expression - should leave 0 or 1 on stack
        Compilable innerCompiler = AstCompilerFactory.getCompiler(innerExpression);
        innerCompiler.compile(mv, ctx);

        // Flip the boolean: push 1 and XOR with the result
        // 0 XOR 1 = 1 (false becomes true)
        // 1 XOR 1 = 0 (true becomes false)
        mv.visitInsn(Opcodes.ICONST_1);
        mv.visitInsn(Opcodes.IXOR);
    }
}
