package com.elminster.jcp.compile.operator.logical;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.operation.LogicalOrExpression;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.base.AbstractAstCompiler;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for logical OR expressions (||).
 *
 * <p>Implements short-circuit evaluation: if left is true, right is not evaluated.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For: left || right
 * [compile left]         // push left value (0 or 1)
 * IFNE trueLabel         // if left is 1 (true), jump to trueLabel
 * [compile right]        // push right value (0 or 1)
 * IFNE trueLabel         // if right is 1 (true), jump to trueLabel
 * ICONST_0               // both false: push 0 (false)
 * GOTO endLabel
 * trueLabel:
 * ICONST_1               // at least one true: push 1 (true)
 * endLabel:
 * }</pre>
 *
 * <h4>Short-Circuit Behavior:</h4>
 * <ul>
 *   <li>If left evaluates to true (1), jump directly to trueLabel without evaluating right</li>
 *   <li>Only evaluate right if left is false (0)</li>
 * </ul>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., 0 or 1] (boolean result as int)</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.operator.logical.OrEvaluator
 */
public class OrCompiler extends AbstractAstCompiler {

    public OrCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        LogicalOrExpression orExpr = (LogicalOrExpression) astNode;
        Expression left = orExpr.getLeft();
        Expression right = orExpr.getRight();

        Label trueLabel = new Label();
        Label endLabel = new Label();

        // Compile left operand
        Compilable leftCompiler = AstCompilerFactory.getCompiler(left);
        leftCompiler.compile(mv, ctx);
        // Short-circuit: if left is true (1), skip right and return true
        mv.visitJumpInsn(Opcodes.IFNE, trueLabel);

        // Left was false, now evaluate right
        Compilable rightCompiler = AstCompilerFactory.getCompiler(right);
        rightCompiler.compile(mv, ctx);
        // If right is true (1), jump to trueLabel
        mv.visitJumpInsn(Opcodes.IFNE, trueLabel);

        // Both false: push 0
        mv.visitInsn(Opcodes.ICONST_0);
        mv.visitJumpInsn(Opcodes.GOTO, endLabel);

        // At least one true: push 1
        mv.visitLabel(trueLabel);
        mv.visitInsn(Opcodes.ICONST_1);

        mv.visitLabel(endLabel);
    }
}
