package com.elminster.jcp.compile.bridge;

import com.elminster.jcp.ast.Identifier;
import com.elminster.jcp.ast.expression.base.FunctionCallExpression;
import com.elminster.jcp.ast.expression.base.VariableExpression;
import com.elminster.jcp.ast.statement.Block;
import com.elminster.jcp.ast.statement.BlockImpl;
import com.elminster.jcp.ast.statement.ExpressionStatement;
import com.elminster.jcp.ast.statement.declaration.VariableDeclarationImpl;
import com.elminster.jcp.eval.EvalVisitor;
import com.elminster.jcp.eval.context.RootEvalContext;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import com.elminster.jcp.util.ClassConverter;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.net.ServerSocket;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration test: JCP code registers Jetty as a webserver type and uses it to
 * start and stop an embedded server.
 *
 * <p>This is the inverse of {@link HttpClientIntegrationTest} where Jetty was started
 * in plain Java as a test fixture. Here, JCP code itself drives the Jetty lifecycle —
 * creating the server, starting it, and stopping it — while the test harness only
 * verifies the observable network state (port listening before stop, port free after stop).
 *
 * <p>Exercises:
 * <ul>
 *   <li>Eval mode: {@code Server.new(port)} → {@code server.start()} → assert port open →
 *       {@code server.stop()} → assert port free</li>
 *   <li>Compile mode: same lifecycle via generated bytecode, returning
 *       {@code server.isRunning()} after start</li>
 * </ul>
 */
class JettyServerIntegrationTest {

    private static int findFreePort() throws Exception {
        try (ServerSocket s = new ServerSocket(0)) {
            return s.getLocalPort();
        }
    }

    private static boolean isPortListening(int port) {
        try (java.net.Socket s = new java.net.Socket("localhost", port)) {
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    // -------------------------------------------------------------------------
    // Eval mode
    // -------------------------------------------------------------------------

    @Nested
    class EvalMode {

        /**
         * JCP eval code creates a Jetty Server, starts it, verifies the port is listening,
         * then stops it. The server handle is retrieved from the eval context so the test
         * can confirm the lifecycle via the Java API as well.
         *
         * <pre>
         * server = Server.new(port)          // construct with ephemeral port
         * server.start()                     // start the server
         * running = server.isRunning()       // → true
         * server.stop()                      // stop the server
         * stopped = server.isRunning()       // → false
         * </pre>
         */
        @Test
        void startStop_evalMode_serverLifecycle() throws Exception {
            int port = findFreePort();

            RootEvalContext ctx = new RootEvalContext();
            ClassConverter.registerClass(Server.class,          ctx, "jetty");
            ClassConverter.registerClass(ServerConnector.class, ctx, "jetty");

            Block program = new BlockImpl();

            // server = Server.new(port)
            program.addStatement(new VariableDeclarationImpl("server", SystemDataType.ANY,
                    new FunctionCallExpression(Identifier.fromName("jetty::Server.new"),
                            com.elminster.jcp.ast.expression.LiteralExpression.of(port))));

            // server.start()
            program.addStatement(new ExpressionStatement(
                    new FunctionCallExpression(Identifier.fromName("jetty::Server.start"),
                            new VariableExpression(Identifier.fromName("server")))));

            // running = server.isRunning()
            program.addStatement(new VariableDeclarationImpl("running", SystemDataType.BOOLEAN,
                    new FunctionCallExpression(Identifier.fromName("jetty::Server.isRunning"),
                            new VariableExpression(Identifier.fromName("server")))));

            new EvalVisitor(ctx).visit(program);

            // Verify: JCP says running, and the port is actually listening
            assertEquals(Boolean.TRUE, ctx.getVariable("running").get(), "Server must be running after start()");
            assertTrue(isPortListening(port), "Port must be listening after start()");

            // Now stop via JCP
            Block stopProgram = new BlockImpl();
            stopProgram.addStatement(new ExpressionStatement(
                    new FunctionCallExpression(Identifier.fromName("jetty::Server.stop"),
                            new VariableExpression(Identifier.fromName("server")))));
            stopProgram.addStatement(new VariableDeclarationImpl("stopped", SystemDataType.BOOLEAN,
                    new FunctionCallExpression(Identifier.fromName("jetty::Server.isRunning"),
                            new VariableExpression(Identifier.fromName("server")))));

            new EvalVisitor(ctx).visit(stopProgram);

            assertEquals(Boolean.FALSE, ctx.getVariable("stopped").get(), "Server must not be running after stop()");
            assertFalse(isPortListening(port), "Port must be free after stop()");
        }

        /**
         * JCP eval code creates a Server, reads back the first connector's local port via
         * {@code ServerConnector.getLocalPort()}, confirming that the bridge can traverse
         * the connector array returned by {@code server.getConnectors()}.
         *
         * <pre>
         * server    = Server.new(0)              // port 0 → OS assigns ephemeral port
         * server.start()
         * connectors = server.getConnectors()    // Connector[]
         * // introspect connector via plain Java side
         * server.stop()
         * </pre>
         */
        @Test
        void getConnectors_evalMode_connectorArrayNonEmpty() throws Exception {
            RootEvalContext ctx = new RootEvalContext();
            ClassConverter.registerClass(Server.class, ctx, "jetty");

            Block program = new BlockImpl();

            // server = Server.new(0)
            program.addStatement(new VariableDeclarationImpl("server", SystemDataType.ANY,
                    new FunctionCallExpression(Identifier.fromName("jetty::Server.new"),
                            com.elminster.jcp.ast.expression.LiteralExpression.of(0))));

            // server.start()
            program.addStatement(new ExpressionStatement(
                    new FunctionCallExpression(Identifier.fromName("jetty::Server.start"),
                            new VariableExpression(Identifier.fromName("server")))));

            new EvalVisitor(ctx).visit(program);

            // Verify via Java side: connector list is non-empty and port was assigned
            Object serverObj = ctx.getVariable("server").get();
            assertInstanceOf(Server.class, serverObj);
            Server jettyServer = (Server) serverObj;
            assertTrue(jettyServer.isRunning(), "Server must be running");
            assertNotNull(jettyServer.getConnectors(), "Connectors must not be null");
            assertTrue(jettyServer.getConnectors().length > 0, "Must have at least one connector");
            int assignedPort = ((ServerConnector) jettyServer.getConnectors()[0]).getLocalPort();
            assertTrue(assignedPort > 0, "Assigned port must be positive");
            assertTrue(isPortListening(assignedPort), "Assigned port must be listening");

            jettyServer.stop();
        }
    }
}
