package com.elminster.jcp.compile.base;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.Statement;
import com.elminster.jcp.ast.statement.Block;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.MethodVisitor;

import java.util.List;

/**
 * Compiler for Block statements.
 *
 * <p>Compiles a sequence of statements within a new scope context.
 * Creates a child CompileContext to manage local variable scope.
 *
 * <h3>Generated Bytecode:</h3>
 * <p>No bytecode is generated for the block itself. The block compiler
 * iterates over child statements and delegates to their respective compilers.
 *
 * <pre>{@code
 * // For block: { stmt1; stmt2; stmt3; }
 * // Generates:
 * [bytecode for stmt1]
 * [bytecode for stmt2]
 * [bytecode for stmt3]
 * }</pre>
 *
 * <h4>Scope Handling:</h4>
 * <p>Variables declared within the block are allocated in a child context,
 * isolating them from the parent scope while still allowing access to
 * parent variables.
 *
 * @see com.elminster.jcp.eval.base.BlockEvaluator
 */
public class BlockCompiler extends AbstractStatementCompiler {

    public BlockCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        Block block = (Block) astNode;
        List<Statement> body = block.getBody();

        // Create a child context for the block scope
        CompileContext blockContext = ctx.createChildContext();

        for (Statement statement : body) {
            Compilable compilable = AstCompilerFactory.getCompiler(statement);
            compilable.compile(mv, blockContext);
        }
    }

}
