package com.elminster.jcp.compile.base;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.statement.ExpressionStatement;
import com.elminster.jcp.compile.Compilable;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for expression statements.
 *
 * <p>Compiles standalone expressions that are used as statements.
 * These are expressions whose return value (if any) is discarded.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For expression statement: foo();
 * [bytecode for function call expression]
 * // Result (if any) is left on stack or popped
 *
 * // For expression statement: x++;
 * [bytecode for increment expression]
 * // Result may need to be popped if expression leaves value on stack
 * }</pre>
 *
 * <h4>Note:</h4>
 * <p>Some expressions leave values on the stack (e.g., post-increment returns
 * the old value). In a full implementation, this compiler would pop unused
 * values to keep the stack balanced.
 *
 * @see com.elminster.jcp.eval.base.ExpressionStatementEvaluator
 */
public class ExpressionStatementCompiler extends AbstractAstCompiler {

    public ExpressionStatementCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        ExpressionStatement exprStmt = (ExpressionStatement) astNode;
        Expression expression = exprStmt.getExpression();

        Compilable compilable = AstCompilerFactory.getCompiler(expression);
        compilable.compile(mv, ctx);

        // Pop the result if the expression leaves a value on the stack
        // TODO: Track whether expressions leave values on the stack
        // For now, we'll handle this on a case-by-case basis
    }
    @Override
    public DataType resolveType(CompileContext ctx) {
        return SystemDataType.VOID;  // Statements don't produce values
    }

}
