package com.elminster.jcp.compile.base;

import com.elminster.jcp.ast.Identifier;
import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.operation.IdentifierExpression;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.context.CompileContext.LocalVariable;
import com.elminster.jcp.compile.exception.CompileException;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import org.objectweb.asm.MethodVisitor;

/**
 * Compiler for identifier expressions (reading a variable by name).
 *
 * <p>Generates bytecode to load a local variable's value onto the operand stack.
 * The appropriate load opcode is determined by the variable's type.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For int/boolean variables:
 * ILOAD index
 *
 * // For double variables:
 * DLOAD index
 *
 * // For reference types (String, Object, struct):
 * ALOAD index
 * }</pre>
 *
 * <h4>Example:</h4>
 * <pre>{@code
 * // Reading variable 'count' (int at index 2):
 * ILOAD 2
 *
 * // Reading variable 'name' (String at index 3):
 * ALOAD 3
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., value]</li>
 * </ul>
 *
 * @throws CompileException if the variable is not defined in the current scope
 */
public class IdentifierCompiler extends AbstractAstCompiler {

    public IdentifierCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        String varName;

        if (astNode instanceof IdentifierExpression) {
            varName = ((IdentifierExpression) astNode).getId();
        } else if (astNode instanceof Identifier) {
            varName = ((Identifier) astNode).getId();
        } else {
            throw new CompileException("Unknown identifier type: " + astNode.getClass().getSimpleName(), getSourceLocation());
        }

        LocalVariable local = ctx.getLocal(varName);
        if (local == null) {
            throw new CompileException("Undefined variable: " + varName, getSourceLocation());
        }

        // Load the variable onto the stack
        int loadOpcode = TypeMapper.getLoadOpcode(local.getType());
        mv.visitVarInsn(loadOpcode, local.getIndex());
    }

    @Override
    public DataType resolveType(CompileContext ctx) {
        String varName;

        if (astNode instanceof IdentifierExpression) {
            varName = ((IdentifierExpression) astNode).getId();
        } else if (astNode instanceof Identifier) {
            varName = ((Identifier) astNode).getId();
        } else {
            return null;  // Unknown identifier type
        }

        LocalVariable local = ctx.getLocal(varName);
        return local != null ? local.getType() : null;
    }
}
