package com.elminster.jcp.compile.base;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.LiteralExpression;
import com.elminster.jcp.ast.expression.literal.BooleanLiteral;
import com.elminster.jcp.ast.expression.literal.DoubleLiteral;
import com.elminster.jcp.ast.expression.literal.IntLiteral;
import com.elminster.jcp.ast.expression.literal.Literal;
import com.elminster.jcp.ast.expression.literal.StringLiteral;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.DataType.SystemDataType;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Compiler for literal expressions (int, boolean, string, double).
 *
 * <p>Generates JVM bytecode to push constant values onto the operand stack.
 * Uses optimized opcodes based on value range for best performance.
 *
 * <h3>Generated Bytecode:</h3>
 *
 * <h4>Integer Literals:</h4>
 * <pre>{@code
 * // For values -1 to 5:
 * ICONST_M1 / ICONST_0 / ICONST_1 / ICONST_2 / ICONST_3 / ICONST_4 / ICONST_5
 *
 * // For byte range (-128 to 127):
 * BIPUSH value
 *
 * // For short range (-32768 to 32767):
 * SIPUSH value
 *
 * // For larger values:
 * LDC value
 * }</pre>
 *
 * <h4>Boolean Literals:</h4>
 * <pre>{@code
 * // true:
 * ICONST_1
 *
 * // false:
 * ICONST_0
 * }</pre>
 *
 * <h4>String Literals:</h4>
 * <pre>{@code
 * LDC "string value"
 * }</pre>
 *
 * <h4>Double Literals:</h4>
 * <pre>{@code
 * // For 0.0:
 * DCONST_0
 *
 * // For 1.0:
 * DCONST_1
 *
 * // For other values:
 * LDC2_W value  // ASM handles this automatically via LDC
 * }</pre>
 *
 * <h4>Null Literal:</h4>
 * <pre>{@code
 * ACONST_NULL
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., value]</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.base.LiteralEvaluator
 */
public class LiteralCompiler extends AbstractAstCompiler {

    public LiteralCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        LiteralExpression literalExpression = (LiteralExpression) astNode;
        Literal literal = literalExpression.getLiteral();
        compileLiteral(literal, mv);
    }

    private void compileLiteral(Literal literal, MethodVisitor mv) {
        // First check for specific interfaces
        if (literal instanceof IntLiteral) {
            compileInt(((IntLiteral) literal).getValue(), mv);
        } else if (literal instanceof DoubleLiteral) {
            compileDouble(((DoubleLiteral) literal).getValue(), mv);
        } else if (literal instanceof BooleanLiteral) {
            compileBoolean(((BooleanLiteral) literal).getValue(), mv);
        } else if (literal instanceof StringLiteral) {
            compileString(((StringLiteral) literal).getValue(), mv);
        } else {
            // Handle generic Literal (e.g., created by Literal.of())
            Object value = literal.getValue();
            if (value instanceof Integer) {
                compileInt((Integer) value, mv);
            } else if (value instanceof Double) {
                compileDouble((Double) value, mv);
            } else if (value instanceof Boolean) {
                compileBoolean((Boolean) value, mv);
            } else if (value instanceof String) {
                compileString((String) value, mv);
            } else if (value == null) {
                mv.visitInsn(Opcodes.ACONST_NULL);
            } else {
                throw new UnsupportedOperationException(
                        "Unsupported literal value type: " + value.getClass().getSimpleName());
            }
        }
    }

    /**
     * Compile an integer literal using the most efficient instruction.
     */
    private void compileInt(int value, MethodVisitor mv) {
        if (value >= -1 && value <= 5) {
            // Use ICONST_M1 to ICONST_5
            mv.visitInsn(Opcodes.ICONST_0 + value);
        } else if (value >= Byte.MIN_VALUE && value <= Byte.MAX_VALUE) {
            // Use BIPUSH for byte range
            mv.visitIntInsn(Opcodes.BIPUSH, value);
        } else if (value >= Short.MIN_VALUE && value <= Short.MAX_VALUE) {
            // Use SIPUSH for short range
            mv.visitIntInsn(Opcodes.SIPUSH, value);
        } else {
            // Use LDC for larger values
            mv.visitLdcInsn(value);
        }
    }

    /**
     * Compile a boolean literal.
     */
    private void compileBoolean(boolean value, MethodVisitor mv) {
        mv.visitInsn(value ? Opcodes.ICONST_1 : Opcodes.ICONST_0);
    }

    /**
     * Compile a string literal.
     */
    private void compileString(String value, MethodVisitor mv) {
        mv.visitLdcInsn(value);
    }

    /**
     * Compile a double literal using the most efficient instruction.
     */
    private void compileDouble(double value, MethodVisitor mv) {
        if (value == 0.0) {
            mv.visitInsn(Opcodes.DCONST_0);
        } else if (value == 1.0) {
            mv.visitInsn(Opcodes.DCONST_1);
        } else {
            // ASM handles LDC2_W automatically for doubles
            mv.visitLdcInsn(value);
        }
    }

    @Override
    public DataType resolveType(CompileContext ctx) {
        LiteralExpression litExpr = (LiteralExpression) astNode;
        Literal literal = litExpr.getLiteral();

        // Check specific literal types
        if (literal instanceof IntLiteral) return SystemDataType.INT;
        if (literal instanceof DoubleLiteral) return SystemDataType.DOUBLE;
        if (literal instanceof BooleanLiteral) return SystemDataType.BOOLEAN;
        if (literal instanceof StringLiteral) return SystemDataType.STRING;

        // Handle generic Literal created by Literal.of() - check value type
        Object value = literal.getValue();
        if (value instanceof Integer) return SystemDataType.INT;
        if (value instanceof Double) return SystemDataType.DOUBLE;
        if (value instanceof Boolean) return SystemDataType.BOOLEAN;
        if (value instanceof String) return SystemDataType.STRING;
        if (value == null) return SystemDataType.ANY;  // null can be any reference type

        return null;  // Unknown literal type
    }
}
