package com.elminster.jcp.compile.base;

import com.elminster.jcp.ast.Node;
import com.elminster.jcp.ast.expression.base.VariableExpression;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.context.CompileContext.LocalVariable;
import com.elminster.jcp.compile.exception.CompileException;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import org.objectweb.asm.MethodVisitor;

/**
 * Compiler for variable expressions (reading a variable).
 *
 * <p>Generates bytecode to load a local variable's value onto the operand stack.
 * Similar to {@link IdentifierCompiler} but handles {@link VariableExpression} AST nodes.
 *
 * <h3>Generated Bytecode:</h3>
 * <pre>{@code
 * // For int/boolean variables:
 * ILOAD index
 *
 * // For double variables:
 * DLOAD index
 *
 * // For reference types (String, Object, struct):
 * ALOAD index
 * }</pre>
 *
 * <h4>Example:</h4>
 * <pre>{@code
 * // Variable expression for 'x' (int at index 1):
 * ILOAD 1
 *
 * // Variable expression for 'point' (struct at index 2):
 * ALOAD 2
 * }</pre>
 *
 * <h4>Stack Effect:</h4>
 * <ul>
 *   <li>Before: [...]</li>
 *   <li>After: [..., value]</li>
 * </ul>
 *
 * @see com.elminster.jcp.eval.base.VariableEvaluator
 * @throws CompileException if the variable is not defined in the current scope
 */
public class VariableCompiler extends AbstractAstCompiler {

    public VariableCompiler(Node astNode) {
        super(astNode);
    }

    @Override
    public void compile(MethodVisitor mv, CompileContext ctx) {
        VariableExpression varExpr = (VariableExpression) astNode;
        String varName = varExpr.getId().getId();

        LocalVariable local = ctx.getLocal(varName);
        if (local == null) {
            throw new CompileException("Undefined variable: " + varName, getSourceLocation());
        }

        // Load the variable onto the stack
        int loadOpcode = TypeMapper.getLoadOpcode(local.getType());
        mv.visitVarInsn(loadOpcode, local.getIndex());
    }

    @Override
    public DataType resolveType(CompileContext ctx) {
        VariableExpression varExpr = (VariableExpression) astNode;
        String varName = varExpr.getId().getId();

        LocalVariable local = ctx.getLocal(varName);
        if (local == null) {
            throw new CompileException(String.format("undefined variable: %s", varName));
        }
        return local.getType();
    }
}
