package com.elminster.jcp.compile;

import com.elminster.jcp.ast.Expression;
import com.elminster.jcp.ast.Statement;
import com.elminster.jcp.ast.statement.Block;
import com.elminster.jcp.ast.statement.declaration.FunctionDeclaration;
import com.elminster.jcp.ast.statement.function.ParameterDef;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.declare.FunctionDeclarationCompiler;
import com.elminster.jcp.compile.util.CompileModeClassConverter;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.module.base.BaseModuleRegister;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Main bytecode generator that compiles a JCP program to a Java class file.
 */
public class BytecodeGenerator implements Opcodes {

    private static final Logger logger = LoggerFactory.getLogger(BytecodeGenerator.class);

    private final String className;
    private final ClassWriter classWriter;
    private CompileContext rootContext;

    /**
     * Create a new bytecode generator.
     *
     * @param className the name of the class to generate (e.g., "Main" or "com/example/Main")
     */
    public BytecodeGenerator(String className) {
        this.className = className;
        this.classWriter = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
    }

    /**
     * Compile a program (Block) to bytecode.
     * Uses two-pass compilation to support forward references:
     * - Pass 1: Register all function signatures
     * - Pass 2a: Generate method for each function
     * - Pass 2b: Generate main() with non-function statements
     *
     * @param program the program AST
     * @return the generated bytecode as a byte array
     */
    public byte[] compile(Block program) {
        logger.info("Compiling program to class: {}", className);

        // Generate class header
        classWriter.visit(
                V1_8,                           // Java 8
                ACC_PUBLIC | ACC_SUPER,         // public class
                className,                      // class name
                null,                           // signature (for generics)
                "java/lang/Object",             // superclass
                null                            // interfaces
        );

        // Generate default constructor
        generateDefaultConstructor();

        // Create root context for compilation
        rootContext = new CompileContext();
        rootContext.setClassName(className);

        // Register module types for external class method calls
        registerModuleTypes(rootContext);

        // Collect function declarations
        List<FunctionDeclaration> functions = new ArrayList<>();
        List<Statement> mainStatements = new ArrayList<>();

        for (Statement stmt : program.getBody()) {
            if (stmt instanceof FunctionDeclaration) {
                functions.add((FunctionDeclaration) stmt);
            } else {
                mainStatements.add(stmt);
            }
        }

        // Pass 1: Register all function signatures
        for (FunctionDeclaration fd : functions) {
            rootContext.registerFunction(
                fd.getId().getId(),
                fd.getParameterDefines(),
                fd.getDataType()
            );
        }

        // Pass 2a: Generate method for each function
        for (FunctionDeclaration fd : functions) {
            generateFunctionMethod(fd);
        }

        // Pass 2b: Generate main method with non-function statements
        generateMainMethod(mainStatements);

        classWriter.visitEnd();

        byte[] bytecode = classWriter.toByteArray();
        logger.info("Generated {} bytes of bytecode", bytecode.length);

        return bytecode;
    }

    /**
     * Generate a static method for a function declaration.
     */
    private void generateFunctionMethod(FunctionDeclaration fd) {
        String methodName = fd.getId().getId();
        String descriptor = TypeMapper.buildMethodDescriptor(
            fd.getParameterDefines(),
            fd.getDataType()
        );

        logger.debug("Generating function method: {} with descriptor: {}", methodName, descriptor);

        // Create method
        MethodVisitor mv = classWriter.visitMethod(
            ACC_PUBLIC | ACC_STATIC,
            methodName,
            descriptor,
            null,
            null
        );
        mv.visitCode();

        // Create function context with isolated local variables
        CompileContext funcCtx = new CompileContext(rootContext);
        funcCtx.setClassName(className);
        funcCtx.setNextLocalIndex(0);  // Reset for static method parameters
        funcCtx.setCurrentFunctionReturnType(fd.getDataType());

        // Delegate body compilation to FunctionDeclarationCompiler
        FunctionDeclarationCompiler compiler = new FunctionDeclarationCompiler(fd);
        compiler.compileBody(mv, funcCtx);

        mv.visitMaxs(0, 0);  // Auto-computed with COMPUTE_FRAMES
        mv.visitEnd();
    }

    /**
     * Generate the default no-arg constructor.
     */
    private void generateDefaultConstructor() {
        MethodVisitor mv = classWriter.visitMethod(
                ACC_PUBLIC,
                "<init>",
                "()V",
                null,
                null
        );

        mv.visitCode();

        // Call super()
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);

        mv.visitInsn(RETURN);
        mv.visitMaxs(0, 0);  // Computed automatically due to COMPUTE_MAXS
        mv.visitEnd();
    }

    /**
     * Generate the main method containing the program code.
     */
    private void generateMainMethod(List<Statement> statements) {
        MethodVisitor mv = classWriter.visitMethod(
                ACC_PUBLIC | ACC_STATIC,
                "main",
                "([Ljava/lang/String;)V",
                null,
                null
        );

        mv.visitCode();

        // Set up root context for main method
        // Index 0 is reserved for the args parameter in static main
        rootContext.setNextLocalIndex(1);  // Skip index 0 (args)
        rootContext.setCurrentFunctionReturnType(DataType.SystemDataType.VOID);

        // Compile each statement using visitor pattern
        CompileVisitor visitor = new CompileVisitor(mv, rootContext);
        for (Statement stmt : statements) {
            visitor.visit(stmt);
        }

        // Return from main
        mv.visitInsn(RETURN);

        mv.visitMaxs(0, 0);  // Computed automatically
        mv.visitEnd();
    }

    /**
     * Get the class name.
     *
     * @return the class name
     */
    public String getClassName() {
        return className;
    }

    /**
     * Get generated classes (structs, etc.) from the compilation context.
     *
     * @return map of class names to bytecode
     */
    public Map<String, byte[]> getGeneratedClasses() {
        if (rootContext != null) {
            return rootContext.getGeneratedClasses();
        }
        return new java.util.HashMap<>();
    }

    /**
     * Compile a program that evaluates an expression and returns a result.
     * Generates a static method named "evaluate" that returns the expression value.
     * Supports function declarations via two-pass compilation.
     *
     * @param program    the program AST (variable declarations, etc.)
     * @param expression the expression to evaluate and return
     * @param returnType the return type of the expression
     * @return the generated bytecode
     */
    public byte[] compileWithReturn(Block program, Expression expression, DataType returnType) {
        logger.info("Compiling program with return to class: {}", className);

        // Generate class header
        classWriter.visit(
                V1_8,
                ACC_PUBLIC | ACC_SUPER,
                className,
                null,
                "java/lang/Object",
                null
        );

        // Generate default constructor
        generateDefaultConstructor();

        // Create compilation context and store as rootContext
        rootContext = new CompileContext();
        rootContext.setClassName(className);

        // Register module types for external class method calls
        registerModuleTypes(rootContext);

        // Collect function declarations and other statements
        List<FunctionDeclaration> functions = new ArrayList<>();
        List<Statement> evalStatements = new ArrayList<>();

        if (program != null) {
            for (Statement stmt : program.getBody()) {
                if (stmt instanceof FunctionDeclaration) {
                    functions.add((FunctionDeclaration) stmt);
                } else {
                    evalStatements.add(stmt);
                }
            }
        }

        // Pass 1: Register all function signatures
        for (FunctionDeclaration fd : functions) {
            rootContext.registerFunction(
                fd.getId().getId(),
                fd.getParameterDefines(),
                fd.getDataType()
            );
        }

        // Pass 2a: Generate method for each function
        for (FunctionDeclaration fd : functions) {
            generateFunctionMethod(fd);
        }

        // Pass 2b: Generate evaluate method with remaining statements
        generateEvaluateMethod(evalStatements, expression, returnType);

        classWriter.visitEnd();

        byte[] bytecode = classWriter.toByteArray();
        logger.info("Generated {} bytes of bytecode", bytecode.length);

        return bytecode;
    }

    /**
     * Generate an evaluate method that returns a value.
     */
    private void generateEvaluateMethod(List<Statement> statements, Expression expression, DataType returnType) {
        String descriptor = "()" + TypeMapper.toDescriptor(returnType);

        MethodVisitor mv = classWriter.visitMethod(
                ACC_PUBLIC | ACC_STATIC,
                "evaluate",
                descriptor,
                null,
                null
        );

        mv.visitCode();

        // Set up root context for evaluate method
        rootContext.setNextLocalIndex(0);  // No args parameter in static evaluate()
        rootContext.setCurrentFunctionReturnType(returnType);

        // Use visitor pattern for compilation
        CompileVisitor visitor = new CompileVisitor(mv, rootContext);

        // Compile the program statements
        for (Statement stmt : statements) {
            visitor.visit(stmt);
        }

        // Compile the expression (leaves value on stack)
        visitor.visit(expression);

        // Return the value
        int returnOpcode = TypeMapper.getReturnOpcode(returnType);
        mv.visitInsn(returnOpcode);

        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }

    /**
     * Register built-in module types (Logger, Assertions, ValueBuffer) for compile-time use.
     * This allows compiled JCP code to call methods on these external Java classes.
     */
    private void registerModuleTypes(CompileContext ctx) {
        List<Class<?>> moduleClasses = BaseModuleRegister.classToRegister();
        for (Class<?> clazz : moduleClasses) {
            CompileModeClassConverter.registerClass(clazz, ctx, "base");
        }
    }
}
