package com.elminster.jcp.compile;

import com.elminster.jcp.ast.statement.Block;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Main bytecode generator that compiles a JCP program to a Java class file.
 */
public class BytecodeGenerator implements Opcodes {

    private static final Logger logger = LoggerFactory.getLogger(BytecodeGenerator.class);

    private final String className;
    private final ClassWriter classWriter;

    /**
     * Create a new bytecode generator.
     *
     * @param className the name of the class to generate (e.g., "Main" or "com/example/Main")
     */
    public BytecodeGenerator(String className) {
        this.className = className;
        this.classWriter = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
    }

    /**
     * Compile a program (Block) to bytecode.
     *
     * @param program the program AST
     * @return the generated bytecode as a byte array
     */
    public byte[] compile(Block program) {
        logger.info("Compiling program to class: {}", className);

        // Generate class header
        classWriter.visit(
                V1_8,                           // Java 8
                ACC_PUBLIC | ACC_SUPER,         // public class
                className,                      // class name
                null,                           // signature (for generics)
                "java/lang/Object",             // superclass
                null                            // interfaces
        );

        // Generate default constructor
        generateDefaultConstructor();

        // Generate main method with the program code
        generateMainMethod(program);

        classWriter.visitEnd();

        byte[] bytecode = classWriter.toByteArray();
        logger.info("Generated {} bytes of bytecode", bytecode.length);

        return bytecode;
    }

    /**
     * Generate the default no-arg constructor.
     */
    private void generateDefaultConstructor() {
        MethodVisitor mv = classWriter.visitMethod(
                ACC_PUBLIC,
                "<init>",
                "()V",
                null,
                null
        );

        mv.visitCode();

        // Call super()
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);

        mv.visitInsn(RETURN);
        mv.visitMaxs(0, 0);  // Computed automatically due to COMPUTE_MAXS
        mv.visitEnd();
    }

    /**
     * Generate the main method containing the program code.
     */
    private void generateMainMethod(Block program) {
        MethodVisitor mv = classWriter.visitMethod(
                ACC_PUBLIC | ACC_STATIC,
                "main",
                "([Ljava/lang/String;)V",
                null,
                null
        );

        mv.visitCode();

        // Create compilation context
        // Index 0 is reserved for the args parameter in static main
        CompileContext ctx = new CompileContext();
        ctx.setClassName(className);
        ctx.setNextLocalIndex(1);  // Skip index 0 (args)

        // Compile the program
        Compilable programCompiler = AstCompilerFactory.getCompiler(program);
        programCompiler.compile(mv, ctx);

        // Return from main
        mv.visitInsn(RETURN);

        mv.visitMaxs(0, 0);  // Computed automatically
        mv.visitEnd();
    }

    /**
     * Get the class name.
     *
     * @return the class name
     */
    public String getClassName() {
        return className;
    }
}
