package com.elminster.jcp.compile;

import com.elminster.jcp.ast.statement.Block;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.util.TraceClassVisitor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Main entry point for compiling JCP programs to Java bytecode.
 */
public class JcpCompiler {

    private static final Logger logger = LoggerFactory.getLogger(JcpCompiler.class);

    /**
     * Compile a program to a .class file.
     *
     * @param program   the program AST
     * @param className the class name (e.g., "Main")
     * @param outputDir the output directory
     * @return the path to the generated .class file
     * @throws IOException if writing fails
     */
    public Path compile(Block program, String className, String outputDir) throws IOException {
        // Generate bytecode
        BytecodeGenerator generator = new BytecodeGenerator(className);
        byte[] bytecode = generator.compile(program);

        // Create output directory if needed
        Path outPath = Paths.get(outputDir);
        Files.createDirectories(outPath);

        // Write .class file
        Path classFile = outPath.resolve(className + ".class");
        Files.write(classFile, bytecode);

        logger.info("Wrote class file: {}", classFile);
        return classFile;
    }

    /**
     * Compile and return bytecode without writing to disk.
     *
     * @param program   the program AST
     * @param className the class name
     * @return the generated bytecode
     */
    public byte[] compileToBytes(Block program, String className) {
        BytecodeGenerator generator = new BytecodeGenerator(className);
        return generator.compile(program);
    }

    /**
     * Compile and load the class into memory.
     *
     * @param program   the program AST
     * @param className the class name
     * @return the loaded class
     */
    public Class<?> compileAndLoad(Block program, String className) {
        byte[] bytecode = compileToBytes(program, className);
        return new ByteArrayClassLoader().defineClass(className, bytecode);
    }

    /**
     * Print the bytecode in human-readable format (for debugging).
     *
     * @param bytecode the bytecode to print
     */
    public void printBytecode(byte[] bytecode) {
        ClassReader reader = new ClassReader(bytecode);
        TraceClassVisitor tracer = new TraceClassVisitor(new PrintWriter(System.out));
        reader.accept(tracer, 0);
    }

    /**
     * Simple class loader for loading generated bytecode.
     */
    private static class ByteArrayClassLoader extends ClassLoader {
        public Class<?> defineClass(String name, byte[] bytecode) {
            return defineClass(name, bytecode, 0, bytecode.length);
        }
    }
}
