package com.elminster.jcp.compile;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Custom ClassLoader that can load multiple generated classes.
 * Used for loading struct classes alongside the main class.
 *
 * <p>When generated bytecode references a class that lives in a dynamically-provided
 * JAR (loaded via a URLClassLoader at runtime), that JAR's classloader is not in the
 * default parent chain. Call {@link #registerClassLoader(ClassLoader)} before loading
 * to make those classes visible.
 */
public class MultiClassLoader extends ClassLoader {

    private final Map<String, byte[]> classDefinitions = new HashMap<>();
    private final List<ClassLoader> delegates = new ArrayList<>();

    public MultiClassLoader() {
        super(MultiClassLoader.class.getClassLoader());
    }

    /**
     * Register an additional classloader to search when a class is not found in the
     * bytecode definitions or the standard parent chain. Intended for dynamically-loaded
     * user JARs whose classloader is not on the application classpath.
     *
     * @param loader the classloader to add as a delegate
     */
    public void registerClassLoader(ClassLoader loader) {
        if (loader != null) {
            delegates.add(loader);
        }
    }

    /**
     * Register a class definition.
     *
     * @param className the fully qualified class name
     * @param bytecode  the class bytecode
     */
    public void defineClass(String className, byte[] bytecode) {
        classDefinitions.put(className, bytecode);
    }

    /**
     * Load and define a class from bytecode.
     *
     * @param className the class name
     * @param bytecode  the bytecode
     * @return the loaded class
     */
    public Class<?> loadClass(String className, byte[] bytecode) {
        classDefinitions.put(className, bytecode);
        try {
            return loadClass(className);
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("Failed to load class: " + className, e);
        }
    }

    @Override
    protected Class<?> findClass(String name) throws ClassNotFoundException {
        byte[] bytecode = classDefinitions.get(name);
        if (bytecode != null) {
            return defineClass(name, bytecode, 0, bytecode.length);
        }
        for (ClassLoader delegate : delegates) {
            try {
                return delegate.loadClass(name);
            } catch (ClassNotFoundException ignored) {
                // try next delegate
            }
        }
        return super.findClass(name);
    }
}
