package com.elminster.jcp.compile;

import com.elminster.jcp.ast.Statement;
import com.elminster.jcp.ast.statement.declaration.MethodDef;
import com.elminster.jcp.ast.statement.declaration.StructDeclaration;
import com.elminster.jcp.ast.statement.declaration.StructFieldDef;
import com.elminster.jcp.ast.statement.function.ParameterDef;
import com.elminster.jcp.compile.context.CompileContext;
import com.elminster.jcp.compile.factory.AstCompilerFactory;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import com.elminster.jcp.eval.data.StructType;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Generates JVM class files for struct/type definitions.
 * Each type becomes a public class with fields, constructor, and methods.
 */
public class StructClassGenerator implements Opcodes {

    private static final Logger logger = LoggerFactory.getLogger(StructClassGenerator.class);

    /**
     * Generate bytecode for a struct class.
     *
     * @param structName the name of the struct (e.g., "Point")
     * @param fields     the list of field definitions
     * @return the generated bytecode
     */
    public byte[] generateStructClass(String structName, List<StructFieldDef> fields) {
        logger.info("Generating struct class: {}", structName);

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);

        // Generate class header
        cw.visit(
                V1_8,                           // Java 8
                ACC_PUBLIC | ACC_SUPER,         // public class
                structName,                     // class name
                null,                           // signature
                "java/lang/Object",             // superclass
                null                            // interfaces
        );

        // Generate public fields
        for (StructFieldDef field : fields) {
            String fieldName = field.getName().getId();
            String descriptor = TypeMapper.toDescriptor(field.getDataType());

            cw.visitField(
                    ACC_PUBLIC,                 // public field
                    fieldName,
                    descriptor,
                    null,                       // signature
                    null                        // default value
            ).visitEnd();
        }

        // Generate constructor
        generateConstructor(cw, structName, fields);

        cw.visitEnd();

        byte[] bytecode = cw.toByteArray();
        logger.info("Generated {} bytes for struct {}", bytecode.length, structName);

        return bytecode;
    }

    /**
     * Generate constructor that initializes all fields.
     */
    private void generateConstructor(ClassWriter cw, String structName, List<StructFieldDef> fields) {
        // Build constructor descriptor: (field1Type, field2Type, ...) -> V
        StringBuilder descriptorBuilder = new StringBuilder("(");
        for (StructFieldDef field : fields) {
            descriptorBuilder.append(TypeMapper.toDescriptor(field.getDataType()));
        }
        descriptorBuilder.append(")V");
        String descriptor = descriptorBuilder.toString();

        MethodVisitor mv = cw.visitMethod(
                ACC_PUBLIC,
                "<init>",
                descriptor,
                null,
                null
        );

        mv.visitCode();

        // Call super()
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);

        // Initialize each field: this.field = paramN
        int paramIndex = 1; // Index 0 is 'this'
        for (StructFieldDef field : fields) {
            String fieldName = field.getName().getId();
            DataType fieldType = field.getDataType();
            String fieldDescriptor = TypeMapper.toDescriptor(fieldType);

            // Load 'this'
            mv.visitVarInsn(ALOAD, 0);

            // Load parameter
            int loadOpcode = TypeMapper.getLoadOpcode(fieldType);
            mv.visitVarInsn(loadOpcode, paramIndex);

            // Store to field
            mv.visitFieldInsn(PUTFIELD, structName, fieldName, fieldDescriptor);

            // Increment param index (double and long take 2 slots)
            paramIndex += TypeMapper.getSize(fieldType);
        }

        mv.visitInsn(RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }

    /**
     * Generate bytecode for a type class with methods.
     *
     * @param decl      the type declaration
     * @param structType the struct type with method info
     * @param parentCtx the parent compilation context
     * @return the generated bytecode
     */
    public byte[] generateTypeClass(StructDeclaration decl, StructType structType, CompileContext parentCtx) {
        String typeName = decl.getId().getId();
        logger.info("Generating type class: {}", typeName);

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);

        // 1. Class header (public class TypeName extends Object)
        cw.visit(V1_8, ACC_PUBLIC | ACC_SUPER, typeName, null, "java/lang/Object", null);

        // 2. Generate fields
        for (StructFieldDef field : decl.getFields()) {
            String fieldName = field.getName().getId();
            String descriptor = TypeMapper.toDescriptor(field.getDataType());
            cw.visitField(ACC_PUBLIC, fieldName, descriptor, null, null).visitEnd();
        }

        // 3. Generate constructor
        if (decl.getConstructor() != null) {
            generateExplicitConstructor(cw, decl, structType, parentCtx);
        } else {
            generateDefaultConstructor(cw, typeName, decl.getFields());
        }

        // 4. Generate instance methods
        for (MethodDef method : decl.getInstanceMethods()) {
            generateInstanceMethod(cw, method, typeName, structType, parentCtx);
        }

        // 5. Generate static methods
        for (MethodDef method : decl.getStaticMethods()) {
            generateStaticMethod(cw, method, typeName, parentCtx);
        }

        cw.visitEnd();

        byte[] bytecode = cw.toByteArray();
        logger.info("Generated {} bytes for type {}", bytecode.length, typeName);
        return bytecode;
    }

    /**
     * Generate default constructor (positional field assignment).
     */
    private void generateDefaultConstructor(ClassWriter cw, String typeName, List<StructFieldDef> fields) {
        // Same as existing generateConstructor but renamed for clarity
        StringBuilder descriptorBuilder = new StringBuilder("(");
        for (StructFieldDef field : fields) {
            descriptorBuilder.append(TypeMapper.toDescriptor(field.getDataType()));
        }
        descriptorBuilder.append(")V");
        String descriptor = descriptorBuilder.toString();

        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC, "<init>", descriptor, null, null);
        mv.visitCode();

        // Call super()
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);

        // Initialize each field
        int paramIndex = 1;
        for (StructFieldDef field : fields) {
            String fieldName = field.getName().getId();
            DataType fieldType = field.getDataType();
            String fieldDescriptor = TypeMapper.toDescriptor(fieldType);

            mv.visitVarInsn(ALOAD, 0);
            mv.visitVarInsn(TypeMapper.getLoadOpcode(fieldType), paramIndex);
            mv.visitFieldInsn(PUTFIELD, typeName, fieldName, fieldDescriptor);
            paramIndex += TypeMapper.getSize(fieldType);
        }

        mv.visitInsn(RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }

    /**
     * Generate explicit constructor from MethodDef.
     */
    private void generateExplicitConstructor(ClassWriter cw, StructDeclaration decl,
                                              StructType structType, CompileContext parentCtx) {
        MethodDef ctor = decl.getConstructor();
        String typeName = decl.getId().getId();
        String descriptor = buildMethodDescriptor(ctor.getParameters(), DataType.SystemDataType.VOID, parentCtx);

        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC, "<init>", descriptor, null, null);
        mv.visitCode();

        // CRITICAL: super() MUST be called first (JVM requirement)
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);

        // Create context that inherits type registrations from parent
        CompileContext ctorCtx = parentCtx.createChildContext();
        ctorCtx.setClassName(typeName);
        ctorCtx.setCurrentFunctionReturnType(DataType.SystemDataType.VOID);

        // 'this' is slot 0
        ctorCtx.allocateLocal("this", structType);

        // Register parameters starting at slot 1
        for (ParameterDef param : ctor.getParameters()) {
            DataType paramType = resolveDataType(param.getDataType(), parentCtx);
            ctorCtx.allocateLocal(param.getId(), paramType);
        }

        // Compile constructor body
        for (Statement stmt : ctor.getBody().getBody()) {
            Compilable compiler = AstCompilerFactory.getCompiler(stmt);
            compiler.compile(mv, ctorCtx);
        }

        mv.visitInsn(RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }

    /**
     * Generate an instance method.
     */
    private void generateInstanceMethod(ClassWriter cw, MethodDef method, String typeName,
                                         StructType structType, CompileContext parentCtx) {
        DataType returnType = resolveDataType(method.getReturnType(), parentCtx);
        String descriptor = buildMethodDescriptor(method.getParameters(), returnType, parentCtx);

        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC, method.getId().getId(), descriptor, null, null);
        mv.visitCode();

        // Create context: 'this' is slot 0, params start at slot 1
        CompileContext methodCtx = parentCtx.createChildContext();
        methodCtx.setClassName(typeName);
        methodCtx.setCurrentFunctionReturnType(returnType);

        // 'this' is slot 0
        methodCtx.allocateLocal("this", structType);

        // Register parameters
        for (ParameterDef param : method.getParameters()) {
            DataType paramType = resolveDataType(param.getDataType(), parentCtx);
            methodCtx.allocateLocal(param.getId(), paramType);
        }

        // Compile method body
        for (Statement stmt : method.getBody().getBody()) {
            Compilable compiler = AstCompilerFactory.getCompiler(stmt);
            compiler.compile(mv, methodCtx);
        }

        // Add implicit return for void methods
        if (returnType == DataType.SystemDataType.VOID) {
            mv.visitInsn(RETURN);
        }

        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }

    /**
     * Generate a static method.
     */
    private void generateStaticMethod(ClassWriter cw, MethodDef method, String typeName,
                                       CompileContext parentCtx) {
        DataType returnType = resolveDataType(method.getReturnType(), parentCtx);
        String descriptor = buildMethodDescriptor(method.getParameters(), returnType, parentCtx);

        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC | ACC_STATIC, method.getId().getId(), descriptor, null, null);
        mv.visitCode();

        // No 'this' for static methods - params start at slot 0
        CompileContext methodCtx = parentCtx.createChildContext();
        methodCtx.setClassName(typeName);
        methodCtx.setCurrentFunctionReturnType(returnType);

        // Register parameters starting at slot 0
        for (ParameterDef param : method.getParameters()) {
            DataType paramType = resolveDataType(param.getDataType(), parentCtx);
            methodCtx.allocateLocal(param.getId(), paramType);
        }

        // Compile method body
        for (Statement stmt : method.getBody().getBody()) {
            Compilable compiler = AstCompilerFactory.getCompiler(stmt);
            compiler.compile(mv, methodCtx);
        }

        // Add implicit return for void methods
        if (returnType == DataType.SystemDataType.VOID) {
            mv.visitInsn(RETURN);
        }

        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }

    /**
     * Resolve data type from type reference.
     * Handles both system types and custom types from context.
     */
    private DataType resolveDataType(DataType type, CompileContext ctx) {
        if (type instanceof DataType.SystemDataType) {
            return type;
        }
        // Try to look up custom type by name
        String typeName = type.getName();
        DataType resolved = ctx.getDataType(typeName);
        if (resolved != null) {
            return resolved;
        }
        // Check system types by name
        for (DataType.SystemDataType sdt : DataType.SystemDataType.values()) {
            if (sdt.getName().equalsIgnoreCase(typeName)) {
                return sdt;
            }
        }
        // Return as-is if not found (will be resolved at runtime)
        return type;
    }

    /**
     * Build method descriptor with proper type resolution.
     */
    private String buildMethodDescriptor(ParameterDef[] params, DataType returnType, CompileContext ctx) {
        StringBuilder sb = new StringBuilder("(");
        if (params != null) {
            for (ParameterDef param : params) {
                DataType paramType = resolveDataType(param.getDataType(), ctx);
                sb.append(TypeMapper.toDescriptor(paramType));
            }
        }
        sb.append(")");
        sb.append(TypeMapper.toDescriptor(returnType));
        return sb.toString();
    }
}
