package com.elminster.jcp.compile;

import com.elminster.jcp.ast.statement.declaration.StructFieldDef;
import com.elminster.jcp.compile.util.TypeMapper;
import com.elminster.jcp.eval.data.DataType;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Generates JVM class files for struct types.
 * Each struct becomes a public class with public fields and a constructor.
 */
public class StructClassGenerator implements Opcodes {

    private static final Logger logger = LoggerFactory.getLogger(StructClassGenerator.class);

    /**
     * Generate bytecode for a struct class.
     *
     * @param structName the name of the struct (e.g., "Point")
     * @param fields     the list of field definitions
     * @return the generated bytecode
     */
    public byte[] generateStructClass(String structName, List<StructFieldDef> fields) {
        logger.info("Generating struct class: {}", structName);

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);

        // Generate class header
        cw.visit(
                V1_8,                           // Java 8
                ACC_PUBLIC | ACC_SUPER,         // public class
                structName,                     // class name
                null,                           // signature
                "java/lang/Object",             // superclass
                null                            // interfaces
        );

        // Generate public fields
        for (StructFieldDef field : fields) {
            String fieldName = field.getName().getId();
            String descriptor = TypeMapper.toDescriptor(field.getDataType());

            cw.visitField(
                    ACC_PUBLIC,                 // public field
                    fieldName,
                    descriptor,
                    null,                       // signature
                    null                        // default value
            ).visitEnd();
        }

        // Generate constructor
        generateConstructor(cw, structName, fields);

        cw.visitEnd();

        byte[] bytecode = cw.toByteArray();
        logger.info("Generated {} bytes for struct {}", bytecode.length, structName);

        return bytecode;
    }

    /**
     * Generate constructor that initializes all fields.
     */
    private void generateConstructor(ClassWriter cw, String structName, List<StructFieldDef> fields) {
        // Build constructor descriptor: (field1Type, field2Type, ...) -> V
        StringBuilder descriptorBuilder = new StringBuilder("(");
        for (StructFieldDef field : fields) {
            descriptorBuilder.append(TypeMapper.toDescriptor(field.getDataType()));
        }
        descriptorBuilder.append(")V");
        String descriptor = descriptorBuilder.toString();

        MethodVisitor mv = cw.visitMethod(
                ACC_PUBLIC,
                "<init>",
                descriptor,
                null,
                null
        );

        mv.visitCode();

        // Call super()
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);

        // Initialize each field: this.field = paramN
        int paramIndex = 1; // Index 0 is 'this'
        for (StructFieldDef field : fields) {
            String fieldName = field.getName().getId();
            DataType fieldType = field.getDataType();
            String fieldDescriptor = TypeMapper.toDescriptor(fieldType);

            // Load 'this'
            mv.visitVarInsn(ALOAD, 0);

            // Load parameter
            int loadOpcode = TypeMapper.getLoadOpcode(fieldType);
            mv.visitVarInsn(loadOpcode, paramIndex);

            // Store to field
            mv.visitFieldInsn(PUTFIELD, structName, fieldName, fieldDescriptor);

            // Increment param index (double and long take 2 slots)
            paramIndex += TypeMapper.getSize(fieldType);
        }

        mv.visitInsn(RETURN);
        mv.visitMaxs(0, 0);
        mv.visitEnd();
    }
}
